### ISSUE TITLE
Failed to autocomplete the PR in Azure Repos

### ISSUE THREAD

**Issue by BrandonStudio** [tinglesoftware/dependabot-azure-devops#1006]
**This may not be a bug**

Dependabot failed to auto complete the PR after successfully auto approved it.

![image](https://github.com/tinglesoftware/dependabot-azure-devops/assets/55647556/a0280044-00e8-4e85-aea9-51af883b2f4d)

part of YAML file:
```yaml
- job: Dependabot
  displayName: 'Dependabot'
  condition: or(eq(variables['Build.Reason'], 'Schedule'), and(eq(variables['Build.Reason'], 'Manual'), ne(variables['manualType'], '0')))

  pool:
    vmImage: 'ubuntu-latest' # requires macos or ubuntu (windows is not supported)

  steps:
  - task: dependabot@1
    inputs:
      setAutoComplete: true
      autoApprove: true
```

I had set permissions for build services following instruction of below image:
![https://learn.microsoft.com/en-us/azure/security/container-secure-supply-chain/articles/container-secure-supply-chain-implementation/cssc-depenadabot](https://learn.microsoft.com/en-us/azure/security/container-secure-supply-chain/media/cssc-dependabot/permissions.png)
What else should I do?
