### ISSUE TITLE
undefined method `directory' for nil:NilClass (NoMethodError) since version 1.26.627

### ISSUE THREAD

**Issue by bNobo** [tinglesoftware/dependabot-azure-devops#1017]
**Describe the bug**
Since version 1.26.627 I get this error when dependabot executes in my AZDO pipeline:

```
bin/update_script.rb:747:in `block (2 levels) in <main>': undefined method `directory' for nil:NilClass (NoMethodError)

      next if updated_files.first.directory != "/" && !title.end_with?(" in #{updated_files.first.directory}")
                                 ^^^^^^^^^^
	from bin/update_script.rb:724:in `each'
	from bin/update_script.rb:724:in `block in <main>'
	from bin/update_script.rb:540:in `each'
	from bin/update_script.rb:540:in `<main>'
##[error]The process '/bin/docker' failed with exit code 1
```

The error get away if I downgrade to version 1.24.596 using `- task: dependabot@1.24.596`

**To Reproduce**
I simply run my pipeline as usual, it contains only one step:

```yaml
steps:
- task: dependabot@1
  displayName: Stargate Dependabot
  inputs:
    azureDevOpsAccessToken: $(PAT)
    gitHubConnection: 'github.com_myconnection'
```

`dependabot.yml` contains this:

```yaml
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker" 
    directory: "/Stargate"
    schedule:
      interval: "daily"
```

**Expected behavior**
I expect dependabot to continue working as before. As a workaround I've downgraded to version 1.24.596

**Extension (please complete the following information):**
 - Host: Azure DevOps Services
 - Version Sprint 234

**Server (please complete the following information):**
 - Region France
 - Version [e.g. 1.2.54]
