### ISSUE TITLE
Azure DevOps - update from dockerimagetag 1.24 to 1.27 causes 401 Unauthorized

### ISSUE THREAD

**Issue by NugetPackage** [tinglesoftware/dependabot-azure-devops#1036]
**Describe the bug**

We have been using dependabot@1 task in Azure DevOps, with dockerImageTag: '1.24'. Everything has been smooth and working great. What we have been missing is the grouping functionality. As of my understanding, version 1.27, released this week, there was a fix for the grouping functionality (https://github.com/dependabot/dependabot-core/pull/9228), and judging by comments from users in dependabot's github page, the grouping functionality seems to be working.

So, we decided to give 1.27 a try, but ran into Unauthorized issues, related to what we think is Personal Access Tokens. The error message looks like this:

```
/tmp/package-dependency-resolution_oFiQP4/Project.csproj : error NU1301: Unable to load the service index for source https://pkgs.dev.azure.com/company/_packaging/nugetfeedname/nuget/v3/index.json.

/usr/local/dotnet/current/sdk/8.0.100/NuGet.targets(156,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/company/_packaging/nugetfeedname/nuget/v3/index.json. [/tmp/package-dependency-resolution_oFiQP4/Project.csproj]

/usr/local/dotnet/current/sdk/8.0.100/NuGet.targets(156,5): error :   Response status code does not indicate success: 401 (Unauthorized). [/tmp/package-dependency-resolution_oFiQP4/Project.csproj]
    0 Warning(s)
    2 Error(s)
```
Our task looks like this: 

```
stages:
  - stage: CheckDependencies
    displayName: 'Check Dependencies'
    jobs:
      - job: Dependabot
        displayName: 'Run Dependabot'
        pool: vmss-linux-swe
        steps:
          - task: dependabot@1
            displayName: 'Run Dependabot'
            inputs:
              dockerImageTag: '1.27'
              setAutoComplete: true
              azureDevOpsAccessToken: $(GIT_ACCESSTOKEN)
```

Access to the nuget feed works (we have a separate Personal Access Token for this). But it seems something is off with `azureDevOpsAccessToken`. The  `GIT_ACCESSTOKEN` is a Personal Access Token, with Code (Read & Write) permissions. 

**To Reproduce**
1. Update from dockerimagetag 1.24 to 1.27

**Expected behavior**
We expect the Personal Access Token to work as it used to in version 1.24, so that dependabot is authorized to create pull requests, using the `azureDevOpsAccessToken`.

**Screenshots**

**Extension (please complete the following information):**
 - Azure DevOps
 - Version 1.27

**Server (please complete the following information):**
 - Region sweden

**Additional context**
Something must have changed internally with the authorization from 1.24 to 1.27. Maybe someone here with deep insights about what we might need to re-configure, or have any additional hints about what to test. Thanks for reading and helping!
