### ISSUE TITLE
AZURE_PORT and AZURE_VIRTUAL_DIRECTORY are ignored for nuget package manager

### ISSUE THREAD

**Issue by EtienneBelanger** [tinglesoftware/dependabot-azure-devops#1054]
**Describe the bug**
I have a repository that uses nuget to manage the dependencies of the different software modules there in. The repository is hosted on an Azure DevOps configured with port (8443) and a /tfs virtual directory, so the repository URL looks like this:

https://tfs.Org.com:443/tfs/Org/MozOrg/_git/ApiAffaires/

I use the extention v.1.27.1.685 and when i try to run the pipeline with minimal settings like the following 

**To Reproduce**
1. run pipeline with minimal settings 
```
name: 'Dependabot'
trigger: none
pool:
  name: Build_Linux
  vmImage: 'ubuntu-latest'

steps:
- task: dependabot@1
```
With config file
```
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    labels:
      - "Nuget Dependencies"
    groups:
      angular:
        applies-to: version-updates
        patterns:
        - "@angular*"
        update-types:
        - "minor"
        - "patch"
```
2. look at the error, we can see that the API endpoint is good but the path to the repo itself is not 
API enpoint (good) : https://tfs.org.com:443/tfs/
repository : https://tfs.Org.com/Org/MozOrg/_git/ApiAffaires/
Should be : https://tfs.Org.com:443/tfs/Org/MozOrg/_git/ApiAffaires/
```
Using '**https://tfs.org.com:443/tfs/**' as API endpoint
Pull Requests shall be linked to milestone (work item) 0
Pull Requests shall be labeled ["Nuget Dependencies"]
Working in Org/MozOrg/_git/ApiAffaires, 'develop' branch under '/' directory
Cloning repository into /home/dependabot/dependabot-updater/tmp/Org/MozOrg/_git/ApiAffaires
/home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.247.0/lib/dependabot/file_fetchers/base.rb:175:in `rescue in clone_repo_contents': Cloning into '/home/dependabot/dependabot-updater/tmp/Org/MozOrg/_git/ApiAffaires'... (Dependabot::RepoNotFound)
fatal: repository 'https://tfs.Org.com/Org/MozOrg/_git/ApiAffaires/' not found
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.247.0/lib/dependabot/file_fetchers/base.rb:163:in `clone_repo_contents'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from bin/update_script.rb:505:in `<main>'
/home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.247.0/lib/dependabot/shared_helpers.rb:429:in `run_shell_command': Cloning into '/home/dependabot/dependabot-updater/tmp/Org/MozOrg/_git/ApiAffaires'... (Dependabot::SharedHelpers::HelperSubprocessFailed)
fatal: repository 'https://tfs.Org.com/Org/MozOrg/_git/ApiAffaires/' not found
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/call_validation.rb:167:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/call_validation.rb:167:in `validate_call_skip_block_type'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/call_validation.rb:109:in `block in create_validator_slow_skip_block_type'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.247.0/lib/dependabot/file_fetchers/base.rb:792:in `block in _clone_repo_contents'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.247.0/lib/dependabot/shared_helpers.rb:265:in `with_git_configured'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.247.0/lib/dependabot/file_fetchers/base.rb:776:in `_clone_repo_contents'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.247.0/lib/dependabot/file_fetchers/base.rb:165:in `clone_repo_contents'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from bin/update_script.rb:505:in `<main>'

```

**Expected behavior**
the repo complete path is wrong
Actual result : https://tfs.Org.com/Org/MozOrg/_git/ApiAffaires/
Expected result : https://tfs.Org.com:443/tfs/Org/MozOrg/_git/ApiAffaires/

**Extension (please complete the following information):**
 - Extension on Azure DevOps [Azure DevOps Server] > [Azure Pipelines] > Dependabot
 - v.1.27.1.685

**Comment by EtienneBelanger** [comment]
Still having the bug in 1.28.0.708

**Comment by hypetsch** [comment]
Not sure, but have you tried specifying extra environment variables? Recently we also tried it out and as far as I remeber we had a similar issue and were able to solve it this way... 

```
steps:
- task: tingle-software.dependabot.dependabot.dependabot@1
  displayName: Dependabot
  inputs:
    dockerImageTag: latest
    extraEnvironmentVariables: 'AZURE_HOSTNAME=<your-host>/tfs;AZURE_ORGANIZATION=<collection>
```
