### ISSUE TITLE
dependency-type: "production" causes error

### ISSUE THREAD

**Issue by jeroensmink98** [tinglesoftware/dependabot-azure-devops#1067]
I'm using the extention to update some NPM packages but only want to update packages that are not dev dependencies, therefore I have the following configured in my `.azuredevops/dependabot.yml`

```yml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "./Website.Library"
    open-pull-requests-limit: 10
    target-branch: "main"
    allow:
      - dependency-type: "production"
 ```
 
 This gives me the following error:
```bash
 Requirements to unlock own
Requirements update strategy #<Dependabot::RequirementsUpdateStrategy::BumpVersions>
bin/update_script.rb:231:in `match?': wrong argument type nil (expected Regexp) (TypeError)
	from bin/update_script.rb:231:in `block in allow_conditions_for'
	from bin/update_script.rb:231:in `each'
	from bin/update_script.rb:231:in `find'
	from bin/update_script.rb:231:in `allow_conditions_for'
```
In the pipeline log I can see it found 14 dependencies even though this project only contains a single non-dev dependency which is `bigpicture` in this case

```bash
Found 14 dependencies
 - bigpicture (2.6.2)
 - @babel/core (7.23.9)
 - @babel/eslint-parser (7.23.9)
 - @babel/preset-env (7.23.9)
 - @tresinternet/design-system (3.0.0)
 - @tresinternet/stylelint-config (2.0.2)
 - @tresinternet/trex (2.6.0)
 - babel-eslint (10.1.0)
 - directory-tree (3.5.1)
 - eslint (8.56.0)
 - gulp (4.0.2)
 - postcss (8.4.33)
 - postcss-preset-env (9.3.0)
 - stylelint (16.2.0)

```
Is the dependency type config available for the extention?

My complete pipeline file looks like this `.azure-pipelines/dependabot.yml`

```yml
schedules:
  - cron: "0 12 * * 0"        
    displayName: Weekly Dependency Updates
    branches:
      include:
        - main
    always: true
    
variables:
  - name: imageToCache
    value: ghcr.io/tinglesoftware/dependabot-updater-npm:1.27

stages:
  - stage: CheckDependencies
    displayName: "Check Dependencies"
    jobs:
      - job: Dependabot
        displayName: "Run Dependabot"
        pool:
          vmImage: "ubuntu-latest"
        steps:

          # Cache Docker image
          - task: Cache@2
            inputs:
              key: docker | "${{ variables.imageToCache }}"
              path: $(Pipeline.Workspace)/docker
              cacheHitVar: DOCKER_CACHE_HIT
            displayName: Cache Docker images

          # Restore Docker image
          - script: |
              docker load -i $(Pipeline.Workspace)/docker/cache.tar
            displayName: Restore Docker image
            condition: and(not(canceled()), eq(variables.DOCKER_CACHE_HIT, 'true'))
          - script: |
              mkdir -p $(Pipeline.Workspace)/docker
              docker pull -q ${{ variables.imageToCache }}
              docker save -o $(Pipeline.Workspace)/docker/cache.tar ${{ variables.imageToCache }}
            displayName: Save Docker image
            condition: and(not(canceled()), or(failed(), ne(variables.DOCKER_CACHE_HIT, 'true')))

          - task: dependabot@1
            displayName: "Run Dependabot"
            inputs:
              useConfigFile: true
              dockerImageTag: 1.27

```
