### ISSUE TITLE
Dependabot task throws "Usage Error: Parse error when loading .yarnrc.yml"

### ISSUE THREAD

**Issue by jw3n** [tinglesoftware/dependabot-azure-devops#1068]
**Describe the bug**
For the past month, we've smoothly utilized the Dependabot task without encountering any issues. However, three days ago, our weekly executed pipeline failed, presenting the following error:

```
Requirements to unlock own
Requirements update strategy #<Dependabot::RequirementsUpdateStrategy::BumpVersions>
Updating @azure/msal-browser from 3.11.0 to 3.11.1
/home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.249.0/lib/dependabot/shared_helpers.rb:429:in 'run_shell_command': Usage Error: Parse error when loading /home/dependabot/dependabot-updater/tmp/<org>/<project>/_git/<repo>/.yarnrc.yml; please check it's proper Yaml (Dependabot::SharedHelpers::HelperSubprocessFailed)

Yarn Package Manager - 4.0.2

  $ yarn <command>

You can also print more details about any of these commands by calling them with the `-h,--help` flag right after the command name.
```

We haven't made any modifications to dependabot.yml or the pipeline definition file, nor have there been changes to our .yarnrc.yml, which maintains the following structure:

```yaml
npmAlwaysAuth: true

npmAuthIdent: "<org>:${NPM_TOKEN}"

npmRegistryServer: <registryUrl>

yarnPath: .yarn/releases/yarn-4.0.2.cjs

```

Our pipeline configuration resembles this:
```yaml
trigger: none # Disable CI trigger

schedules:
  - cron: '0 4 * * 3' # on every wednesday at 4am UTC
    always: true # run even when there are no code changes
    branches:
      include:
        - develop
    batch: true
    displayName: Daily
pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: dependabot@1
    inputs:
      extraEnvironmentVariables: NPM_TOKEN=$(System.AccessToken)
      gitHubConnection: github-dependabot
    env:
      NPM_TOKEN: $(System.AccessToken)
```

and the dependabot.yml within the .azuredevops folder structured as follows:

```yaml
version: 2
registries:
  web-components:
    type: npm-registry
    url: <registryUrl>
    token: PAT:${{NPM_TOKEN}}
updates:
  - package-ecosystem: npm
    directory: '/'
    open-pull-requests-limit: 100
    registries: 
      - web-components
    target-branch: develop
    schedule:
      interval: weekly
```

**To Reproduce**
1. Use a yarn project and configure it for dependabot
2. Run a pipeline with the dependabot task

**Expected behavior**
The task/pipeline should ran through as expected without throwing an error.

**Extension:**
 - Host: Azure DevOps
 - Version 1
