### ISSUE TITLE
Python Packages "The user 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this"

### ISSUE THREAD

**Issue by cpressland** [tinglesoftware/dependabot-azure-devops#1094]
**Describe the bug**
We use Poetry to manage dependencies for our Python applications, as well as package them for shipping into Docker Containers. We use Azure DevOps as an artifact store for some private packages.

When Dependabot runs via GitHub, it crashes out when trying to fetch one of these dependencies:
```
  proxy | 2024/04/17 15:25:23 [115] GET https://pkgs.dev.azure.com:443/<org_name>/_packaging/<org_name>/pypi/simple/retry-tasks-lib/
  proxy | 2024/04/17 15:25:23 [115] * authenticating python index request (host: pkgs.dev.azure.com)
  proxy | 2024/04/17 15:25:23 [115] 200 https://pkgs.dev.azure.com:443/<org_name>/_packaging/<org_name>/pypi/simple/retry-tasks-lib/
  proxy | 2024/04/17 15:25:24 [117] GET https://pkgs.dev.azure.com:443/<org_name>/_packaging/000c7077-6e85-42db-85aa-bf6783750a0b/pypi/download/retry-tasks-lib/2.2.1/retry_tasks_lib-2.2.1-py3-none-any.whl
  proxy | 2024/04/17 15:25:24 [117] 401 https://pkgs.dev.azure.com:443/<org_name>/_packaging/000c7077-6e85-42db-85aa-bf6783750a0b/pypi/download/retry-tasks-lib/2.2.1/retry_tasks_lib-2.2.1-py3-none-any.whl
  proxy | 2024/04/17 15:25:24 [117] Remote response: {"$id":"1","innerException":null,"message":"TF400813: The user 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}
  proxy | 2024/04/17 15:25:24 [119] HEAD https://pkgs.dev.azure.com:443/<org_name>/_packaging/000c7077-6e85-42db-85aa-bf6783750a0b/pypi/download/retry-tasks-lib/2.2.1/retry_tasks_lib-2.2.1-py3-none-any.whl
```

I have reviewed #50, https://github.com/dependabot/dependabot-core/issues/6676 and a whole bunch of other issues I've lost track of now.

**To Reproduce**
* Our Dependabot YAML looks like this:
```yaml
version: 2
registries:
  python-azure:
    url: https://pkgs.dev.azure.com/<org_name>/_packaging/<org_name>/pypi/simple
    type: python-index
    token: "${{ secrets.AZURE_DEVOPS_PAT }}:"
    replaces-base: true
updates:
  - package-ecosystem: "pip"
    insecure-external-code-execution: allow
    directory: "/"
    schedule:
      interval: "weekly"
    registries:
      - python-azure
    assignees:
      - cpressland
```

Note that we've tried a ton of variations of `token`, examples include:
* `${{ secrets.AZURE_DEVOPS_PAT }`
* `":${{ secrets.AZURE_DEVOPS_PAT }"`
* `<org_name>:${{ secrets.AZURE_DEVOPS_PAT }}`
* `PAT:${{ secrets.AZURE_DEVOPS_PAT }`
* `"${{ secrets.AZURE_DEVOPS_PAT }:"`
* `"PAT:${{ secrets.AZURE_DEVOPS_PAT }:"`

All lead to the same failure condition.

This token works fine in Poetry as well a pip directly, I've also swapped the token from one with ReadOnly acess to one with Read/Write just to rule that out, and that didn't make any difference.

Any other suggestions would be greatly appreciated.

**Expected behavior**
Dependabot successfully connects to Azure DevOps Artifacts.
