### ISSUE TITLE
Question: Could you give an example on how to use Caching for Docker?

### ISSUE THREAD

**Issue by XzaR90** [tinglesoftware/dependabot-azure-devops#113]
Could you give an example on how to use Caching for Docker in Azure Pipelines?
Thank you.

```
trigger: none

schedules:
- cron: "0 2 * * 0"
  always: true
  branches:
    include:
    - dev
  batch: true
  displayName: Weekly

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Cache@2
  displayName: Cache Docker images
  inputs:
    key: 'docker | cache'
    path: $(Pipeline.Workspace)/docker
    cacheHitVar: DOCKER_CACHE_HIT
- script: |
    docker load -i $(Pipeline.Workspace)/docker/cache.tar
    displayName: Restore Docker image
    condition: and(not(canceled()), eq(variables.DOCKER_CACHE_HIT, 'true'))
- task: dependabot@1
  displayName: Run Dependabot
  env:
    PAS_TOKEN: $(PAS_TOKEN)
  inputs:
    useConfigFile: true
    azureDevOpsAccessToken: $(PAS_TOKEN)
- script: |
    mkdir -p $(Pipeline.Workspace)/docker
    docker save -o $(Pipeline.Workspace)/docker/cache.tar cache
    displayName: Save Docker image
    condition: and(not(canceled()), or(failed(), ne(variables.DOCKER_CACHE_HIT, 'true')))
```
