### ISSUE TITLE
Mismatch between Dependabot API and Azure DevOps API - Pull request cannot be activated

### ISSUE THREAD

**Issue by eimerreis** [tinglesoftware/dependabot-azure-devops#120]
Hi Guys,

Thanks for making this extension, I'd really like to use it in our Azure DevOps tenant. 
Unfortunately I cannot get the build step running because dependabot is not able to find my traget branch (master). 

`Pull Request creation failed with status 400. Message: TF401398: The pull request cannot be activated because the source and/or the target branch no longer exists, or the requested refs are not branches (StandardError)`

I think this is related to the Azure DevOps REST API, expecting branch names being prefixed with `refs/heads`. At least thats what I suppose based on [this thread](https://developercommunity.visualstudio.com/t/cannot-create-pull-request-via-rest-api/568288)

Once I change my target branch to have that prefix, e.g. `refs/heads/master`, dependabot itself fails way earlier with the following error message: `rescue in commit': Dependabot::BranchNotFound (Dependabot::BranchNotFound)`

I thought this is related to #64 but I didnt see how my problem is similar to the one of that issue, except for the error message

My pipeline looks like this:

```yml
variables:
  DEPENDABOT_EXTRA_CREDENTIALS: '[{"type":"npm_registry","token":"$(System.AccessToken)","registry":"pkgs.dev.azure.com/tapioone/_packaging/NpmFeed/npm/registry"}]' # put the credentials for private registries and feeds

jobs:
  - job: Dependabot
    # pool:
    #   name: Tapio VS 2019
      # demands:
      #   - Agent.ComputerName -equals build-vs2019-03 # pin to 03 agent for testing
    steps:
      - task: dependabot@1
        inputs:
          packageManager: 'npm'
          directory: 'Source/Frontend/packages/twinio.mobile'
          versioningStrategy: 'auto'
          targetBranch: 'master'
``` 

Don't know if this is relevant, but we're in the scope of a monorepo, thats managing multiple npm packages using yarn workspaces.

Thanks in advance
