### ISSUE TITLE
System.ComponentModel.DataAnnotations.ValidationException: The Directory field is required.

### ISSUE THREAD

**Issue by MarkTallentire** [tinglesoftware/dependabot-azure-devops#1275]
**Describe the bug**
Erorr thrown when running dependabot server System.ComponentModel.DataAnnotations.ValidationException: The Directory field is required.

Directory field is optional if directories is set based on the official dependabot configuration. https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directories

**Categorization**
- [ X ] This is not a permissions issue (Seek help at https://github.com/tinglesoftware/dependabot-azure-devops/discussions/1245)

**To Reproduce**
Run the Azure deployment of the Dependabot Server. Setup a configuration such as:

````
version: 2
open-pull-requests-limit: 10

updates:
  - package-ecosystem: "nuget"
    directories: 
      - "/src/*"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:      
      prefix: "[Chore]"


````

**Expected behavior**
For the dependabot configuration to be processed

**Screenshots**

![image](https://github.com/user-attachments/assets/fd88b079-05ec-400c-8c7a-8962d2bd6a51)

**Server (please complete the following information):**
West Europe
Latest (Downloaded 15/08/2024)

**Additional context**
