### ISSUE TITLE
vNext groups in dependabot.yml file seems ignored

### ISSUE THREAD

**Issue by jmagano-ena** [tinglesoftware/dependabot-azure-devops#1334]
**Describe the bug**
I’m trying to use the group feature with dependabot. In my .github/dependabot.yml file, I added a parameter to group some packages, and I expected to have only one PR for each group. But, when I run my dependabot pipeline, dependabot keeps create one PR for each package, and seem ignore my configuration. The rest of the configuration of my file, like the schedule interval, is considered without any issue.

**Categorization**
- [X] This is not a permissions issue (Seek help at https://github.com/tinglesoftware/dependabot-azure-devops/discussions/1245)

**To Reproduce**
File of my pipeline
```yml
trigger: none

schedules:
  - cron: "0 2 1 * *"
    always: true # run even when there are no code changes
    branches:
      include:
        - main
        - releases/*
    batch: true
    displayName: 🕑 Dependabot

pool: "Linux"

steps:
  - task: NuGetAuthenticate@1

  - task: dependabot@1
    inputs:
      useVNext: true
```

My dependabot.yml configuration file:
```yml
version: 2
registries:
  custom-nuget:
    type: nuget-feed
    url: https://xxxxxx
    token: PAT:xxxxxx
updates:
  - package-ecosystem: "nuget"
    directory: "/Sources"
    registries:
      - custom-nuget
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 10
    groups:
      tests:
        patterns:
          - "PackageA.*"
          - "PackageB"
      repository-management:
        patterns:
          - "PackageC"
          - "PackageD.*"
```

**Expected behavior**
One PR for each group.

**Additional context**
The [documentation](https://github.com/tinglesoftware/dependabot-azure-devops/blob/main/docs/updater.md) indicates only the environmental variable for configure group, and have a link to the syntax to use in dependabot.yml. I don’t know clearly if this functionality is working in this way or not.
