### ISSUE TITLE
Not all the dependency files are getting updated in the Pull Request using depenadbot v2

### ISSUE THREAD

**Issue by vishnuprakash9845** [tinglesoftware/dependabot-azure-devops#1407]
**Describe the bug**
I am managing NuGet packages, specifically SumNumbers, in Azure Artifacts and have configured the following dependabot.yml file for version updates. The pipeline triggers using Dependabot with the below configuration. In my Test Repo at two places have the .csproj file which has the package reefrence of the nuget in src folder and test folder. 

My Repository Structure

![image](https://github.com/user-attachments/assets/fa610603-b1cb-483c-ae06-c937a05ad935)

**dependabot.yml**
```
version: 2
updates:
-package-ecosystem: "nuget" # See documentation for possible values
  directory: "/" # Location of package manifests
  target-branch: "main"
  labels:
    - "SumNumbers"
    - "Nuget dependencies"
  commit-message:
      prefix: "Nuget SumNumbers Dependency Update"
  allow:
    - dependency-name: "SumNumbers"
  open-pull-requests-limit: 5
  registries:
      - azure_artifacts
registries:
  azure_artifacts:
    type: "nuget-feed"
    url: "https://pkgs.dev.azure.com/MyProject/47ad2345353535/_packaging/learningfeed/nuget/v3/index.json"
    token: "PAT:<PAT_TOKEN>"
```

**azure-pipelines.yml**

```
- task: dependabot@2
  inputs:
    setAutoComplete: true
    mergeStrategy: 'noFastForward'
    autoApprove: false
    autoApproveUserToken: '<PAT>'
    azureDevOpsAccessToken: '<PAT>'
```

_**In the logs, Dependabot successfully detects the latest NuGet package versions (from 2.0.14 to 2.0.16). Its created the pull request with Dependabot V2, with only one file its updating in src folder, for test folder its not updating the file..**_ 

![image](https://github.com/user-attachments/assets/909a0d62-9472-4f9d-a921-d61f7dbcc34c)

I have tried to update the  **dependabot.yml**

```
version: 2
updates:
-package-ecosystem: "nuget" # See documentation for possible values
  directories:
    - "**/*"
  target-branch: "main"
```

but getting error as 

_**[error]Failed to create pull request: Error: Request to 'https://dev.azure.com/xxxx/_apis/git/repositories/xxxx/pushes' failed: 409 Conflict**_

**Categorization**
- [x] This is not a permissions issue (Seek help at https://github.com/tinglesoftware/dependabot-azure-devops/discussions/1245)

**Expected behavior**
The new Dependabot V2 should able to detect nuget version in all the src and test folders .csproj files and create a PR.

**Logs and screenshots**
This logs for  **dependabot.yml** including directories

```
version: 2
updates:
-package-ecosystem: "nuget" # See documentation for possible values
  directories:
    - "**/*"
  target-branch: "main"
```

**_{"$id":"1","innerException":null,"message":"TF401028: The reference 'refs/heads/dependabot/nuget/test-dev1/SumNumbers-2.0.16' has already been updated by another client, so you cannot update it. Please try again.","typeName":"Microsoft.TeamFoundation.Git.Server.GitReferenceStaleException, Microsoft.TeamFoundation.Git.Server","typeKey":"GitReferenceStaleException","errorCode":0,"eventId":3000}
##[error]Failed to create pull request: Error: Request to 'https://dev.azure.com/xxxx/_apis/git/repositories/xxxx/pushes' failed: 409 Conflict_**
![image](https://github.com/user-attachments/assets/b541a910-b264-465a-8cc8-e18ff5b2570c)

**Extension (please complete the following information):**
 - Host Azure DevOps
 - Version 1.36.0.987

**Additional context**
I have recently migrated to Dependabot V2 from the previous version. In the past, the configuration worked smoothly for triggering PRs in Azure Pipelines with dependabot@1. However, the new setup seems to work partially during the PR creation step, despite successful version detection. I request someone from community to help on this.

**Comment by rhyskoedijk** [comment]
Does your project have a `.sln` file? 
If you want one pull request that updates both projects, you'll need to create a solution file in the root dir that references both projects. e.g.
```
~/SumNumbers.sln
  ~/src/src.csproj
  ~/test/test.csproj
```
```yaml
updates:
-package-ecosystem: "nuget"
  directory: '/'
  target-branch: "main"
```

If you want two pull requests, one for each sub-directory, try this config:
```yaml
updates:
-package-ecosystem: "nuget"
  directories:
    - "/src"
    - "/test"
  target-branch: "main"
```

Using `directories: "**/*"` _might_ work better in the latest version (1.36.1); However, I haven't tested that scenario yet, but will investigate it when I have time. If possible, I'd suggest using one of the above two options.

**Comment by vishnuprakash9845** [comment]
> @vishnuprakash9845, does your project have a `.sln` file? If you want one pull request that updates both projects, you'll need to create a solution file in the root dir that references both projects. e.g.
> 
> ```
> ~/SumNumbers.sln
>   ~/src/src.csproj
>   ~/test/test.csproj
> ```
> 
> ```yaml
> updates:
> -package-ecosystem: "nuget"
>   directory: '/'
>   target-branch: "main"
> ```
> 
> If you want two pull requests, one for each sub-directory, try this config:
> 
> ```yaml
> updates:
> -package-ecosystem: "nuget"
>   directories:
>     - "/src"
>     - "/test"
>   target-branch: "main"
> ```
> 
> Using `directories: "**/*"` _might_ work better in the latest version (1.36.1); However, I haven't tested that scenario yet, but will investigate it when I have time. Using globs to match every possible directory is probably causing some issues with the branch names not being unique enough, if I had to guess. If possible, I'd suggest using one of the above two options.

@rhyskoedijk  Thank you for the quock response.

Yes, my project contains a solution that references both projects (located inside the src and test directories). 
**I initially tried the following configuration for one pull request to update both projects:**

```
~/SumNumbers.sln
  ~/src/src.csproj
  ~/test/test.csproj

updates:
  - package-ecosystem: "nuget"
    directory: '/'
    target-branch: "main"
```
However, this approach resulted in a pull request that only contained changes for the src project.

**Next, I tried this configuration for two separate pull requests (one for each sub-directory):**

```
updates:
  - package-ecosystem: "nuget"
    directories:
      - "/src"
      - "/test"
    target-branch: "main"
```

Unfortunately, I encountered the same issue, and I received the following error message:
_{"$id":"1","innerException":null,"message":"TF401028: The reference 'refs/heads/dependabot/nuget/main/xxx-2.0.16' has already been updated by another client, so you cannot update it. Please try again.","typeName":"Microsoft.TeamFoundation.Git.Server.GitReferenceStaleException, Microsoft.TeamFoundation.Git.Server","typeKey":"GitReferenceStaleException","errorCode":0,"eventId":3000}_

![image](https://github.com/user-attachments/assets/b84af1f5-3395-4649-8cfe-838750835e94)


The error seems to indicate a conflict with an existing branch update, likely due to simultaneous changes being made by another process.

**Comment by vishnuprakash9845** [comment]
Sometimes observed this error also for the below dependabot.yml config file

```
updates:
  - package-ecosystem: "nuget"
    directories:
      - "/src"
      - "/test"
    target-branch: "main"
```

![image](https://github.com/user-attachments/assets/e432e1c1-aaeb-4a18-bbbc-c96b7984940a)
