### ISSUE TITLE
Fails to parse local folders with a relative path

### ISSUE THREAD

**Issue by nicolasproton** [tinglesoftware/dependabot-azure-devops#1411]
**Describe the bug**
I am running TaskV2 with the `directories` options. As it parses each sub-folders, it fails to find dependencies that are located in other relative paths. I have tried adding an `ignore` statement but without success
```yaml
    ignore:
      - dependency-name: 'datahub-*'
```
I am using tox and pytest for the unit tests execution, which requires the local dependencies to be also defined in the `pyproject.toml` file.

**Expected behaviour**
I would expect dependabot to parse any folder using a relative path (or being able to `ignore` local folders)

**Logs and screenshots**
`.azuredevops/dependabot.yml`
```yaml
  - package-ecosystem: "pip"
    directories:
      - "/"
      - "/services/*"
    # schedule is ignored, using pipeline scheduled triggers instead.
    schedule:
      interval: "daily"
    versioning-strategy: "lockfile-only"
    groups:
      all-dependencies-python:
        applies-to: "version-updates"
        patterns:
          - "*" # Update all dependencies
```

`services/access_control/pyproject.toml`
```yaml
[tool.poetry]
name = "datahub-access-control"
version = "0.1.0"
description = ""
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.group.dev.dependencies]
aws-lambda-powertools = "^2"
datahub-shared-services = { path = "../shared_services" }
```

Error Logs
```
...
updater | 2024/10/17 12:15:34 INFO <job_update_0_pip_all> Filtered out 6 yanked versions
updater | 2024/10/17 12:15:34 INFO <job_update_0_pip_all> Filtered out 164 pre-release versions
updater | 2024/10/17 12:15:34 INFO <job_update_0_pip_all> Latest version is 3.1.0
updater | 2024/10/17 12:15:36 WARN <job_update_0_pip_all> Path /home/dependabot/dependabot-updater/tmp/20241017-2931-64xo49/shared_services for datahub-shared-services does not exist
updater | Creating virtualenv datahub-orchestration-framework-KVs4QgZy-py3.12 in /home/dependabot/.cache/pypoetry/virtualenvs
updater | Updating dependencies
updater | Path /home/dependabot/dependabot-updater/tmp/20241017-2931-64xo49/shared_services for shared-services does not exist
updater | Resolving dependencies...
updater | 
updater | Path /home/dependabot/dependabot-updater/tmp/20241017-2931-64xo49/shared_services for datahub-shared-services does not exist
  proxy | 2024/10/17 12:15:36 [010] POST http://host.docker.internal:33029/update_jobs/update_0_pip_all/record_update_job_error
{"data":{"error-type":"unknown_error","error-details":null},"type":"record_update_job_error"}
  proxy | 2024/10/17 12:15:36 [010] 200 http://host.docker.internal:33029/update_jobs/update_0_pip_all/record_update_job_error
updater | 2024/10/17 12:15:36 ERROR <job_update_0_pip_all> Error processing aws-lambda-powertools (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | 2024/10/17 12:15:36 ERROR <job_update_0_pip_all> Path /home/dependabot/dependabot-updater/tmp/20241017-2931-64xo49/shared_services for datahub-shared-services does not exist
updater | Creating virtualenv datahub-orchestration-framework-KVs4QgZy-py3.12 in /home/dependabot/.cache/pypoetry/virtualenvs
updater | Updating dependencies
updater | Path /home/dependabot/dependabot-updater/tmp/20241017-2931-64xo49/shared_services for shared-services does not exist
updater | Resolving dependencies...
updater | 
updater | Path /home/dependabot/dependabot-updater/tmp/20241017-2931-64xo49/shared_services for datahub-shared-services does not exist
updater | 2024/10/17 12:15:36 ERROR <job_update_0_pip_all> /home/dependabot/common/lib/dependabot/shared_helpers.rb:463:in `run_shell_command'
updater | 2024/10/17 12:15:36 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:167:in `bind_call'
...
```

**Extension:**
 - Host: Azure DevOps
 - dependabot (2.36.1000)
 - TaskV2

**Comment by nicolasproton** [comment]
Thanks. I checked and it could be somewhat related to https://github.com/dependabot/dependabot-core/issues/9554 but the error is a little different. So it is hard to tell if that's the same issue.
`../shared_services` would just need its own `pyproject.toml` but nothing else in order for you to test. Mine is set as below

`/services/shared_services/pyproject.toml`
```toml
[tool.poetry]
name = "datahub-shared-services"
version = "0.1.0"
description = ""
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
aws-requests-auth = "^0"
packaging = "^24"
typing-extensions = "^4"
msal = "^1"
pydantic = "^2"

[tool.poetry.group.dev.dependencies]
aws-lambda-powertools = "^2"

```

**Comment by rhyskoedijk** [comment]
@nicolasproton I'm having trouble reproducing this issue, could you confirm if this matches your configuration?

![image](https://github.com/user-attachments/assets/56f5fcf8-379f-45b2-9a26-fc147a48ec39)

`dependabot.yml`
```yaml
version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "Test-Pip-1411/"
      - "Test-Pip-1411/services/*"
    versioning-strategy: "lockfile-only"
    groups:
      all-dependencies-python:
        applies-to: "version-updates"
        patterns:
          - "*"
```

`Test-Pip-1411/services/access_control/pyproject.toml`
```toml
[tool.poetry]
name = "datahub-access-control"
version = "0.1.0"
description = ""
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.group.dev.dependencies]
aws-lambda-powertools = "^2"
datahub-shared-services = { path = "../shared_services" }
```

`Test-Pip-1411/services/shared_services/pyproject.toml`
```toml
[tool.poetry]
name = "datahub-shared-services"
version = "0.1.0"
description = ""
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
aws-requests-auth = "^0"
packaging = "^24"
typing-extensions = "^4"
msal = "^1"
pydantic = "^2"

[tool.poetry.group.dev.dependencies]
aws-lambda-powertools = "^2"
```
