### ISSUE TITLE
Nuget Package Authorization Error

### ISSUE THREAD

**Issue by ahmetgul93** [tinglesoftware/dependabot-azure-devops#1412]
**Describe the bug**
I couldn't pass token into dependabot.yml to authenticate private feed.

This my dependabot.yml

```
version: 2
registries:
  azure-artifacts:
    type: nuget-feed
    key: "bbb-feed"
    url: "https://aaa.pkgs.visualstudio.com/bbb/_packaging/bbb-feed/nuget/v3/index.json"
    token: ':$(PAT)'
updates:
  - package-ecosystem: "nuget"
    directories: [ '/xxx/yyy/*' ]
    registries:
      - azure-artifacts
    schedule:
      interval: "weekly"
    target-branch: "main"
    commit-message:
      prefix: "outdated package upgrade"
    open-pull-requests-limit: 10
```

this my stage in azurepipeline.yaml

```
  - stage: CheckDependencies
    jobs:
      - job: Dependabot
        displayName: 'Run Dependabot'
        steps:
          - task: dependabot@1
            displayName: 'Run Dependabot'
            inputs:
              useUpdateScriptvNext: true
            env:
              PAT: $(System.AccessToken)
```
              
After 20 min run (probably it is timeout ), it gets below error;

Discovery JSON content: {
  "Path": "/xxx/yyy/zzz", 
  "IsSuccess": true,
  "Projects": [],
  "DirectoryPackagesProps": null,
  "GlobalJson": null,
  "DotNetToolsJson": null,
  "ErrorType": "AuthenticationFailure",
  "ErrorDetails": "(https://aaa.pkgs.visualstudio.com/bbb/_packaging/bbb-feed/nuget/v3/index.json)"
  
  In the pipeline log I see this argument in the docker run;
  
  -e DEPENDABOT_EXTRA_CREDENTIALS=[{"type":"nuget_feed","key":"bbb-feed","token":"${PAT}","url":"https://aaa.pkgs.visualstudio.com/bbb/_packaging/bbb-feed/nuget/v3/index.json"}] 
  
 **The following source could not be reached as it requires authentication (and any provided details were invalid or lacked the required permissions):** ([https://api.nuget.org/v3/index.json|https://aaa.pkgs.visualstudio.com/bbb/_packaging/bbb-feed/nuget/v3/index.json...]
 
 Could you please how can I pass this authentication error?
