### ISSUE TITLE
(NoMethodError) on Private Registry

### ISSUE THREAD

**Issue by caglanurcetinn** [tinglesoftware/dependabot-azure-devops#1426]
**Describe the bug**
I got this error when my dependabot try to create PR for private Nuget package in Azure Devops. 

2024/10/22 08:40:23 INFO <job_1729586364> Checking if AAA.Common.Http 2.0.1 needs updating
🌍 --> GET https://xxx.pkgs.visualstudio.com/aaa/_packaging/private-feed/nuget/v3/index.json
🌍 <-- 200 https://xxx.pkgs.visualstudio.com/aaa/_packaging/private-feed/nuget/v3/index.json
🌍 --> GET https://xxx.pkgs.visualstudio.com/744cec9e-c94a-41aa-a3a1-ed866b65b436/_packaging/d7ac292f-e20f-4e34-918f-5406eb9364ee/nuget/v3/registrations2/AAA.Common.Http/index.json
🌍 <-- 200 https://xxx.pkgs.visualstudio.com/744cec9e-c94a-41aa-a3a1-ed866b65b436/_packaging/d7ac292f-e20f-4e34-918f-5406eb9364ee/nuget/v3/registrations2/AAA.Common.Http/index.json
🌍 --> GET https://api.nuget.org/v3/registration5-gz-semver2/AAA.Common.Http/index.json
🌍 <-- 404 https://api.nuget.org/v3/registration5-gz-semver2/AAA.Common.Http/index.json
🌍 --> GET https://api.nuget.org/v3-flatcontainer/AAA.Common.Http/2.0.1/AAA.Common.Http.nuspec
🌍 <-- 404 https://api.nuget.org/v3-flatcontainer/AAA.Common.Http/2.0.1/AAA.Common.Http.nuspec
2024/10/22 08:40:24 INFO <job_1729586364> Latest version is 2.0.2
2024/10/22 08:40:24 ERROR <job_1729586364> Error processing AAA.Common.Http **(NoMethodError)**
2024/10/22 08:40:24 ERROR <job_1729586364> undefined method `contains_dependency?' for an instance of Array
2024/10/22 08:40:24 ERROR <job_1729586364> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:255:in `block in pr_exists_for_latest_version?'
2024/10/22 08:40:24 ERROR <job_1729586364> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:255:in `any?'
2024/10/22 08:40:24 ERROR <job_1729586364> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:255:in `pr_exists_for_latest_version?'

my dependabot.yaml

```
version: 2
registries:
  artifacts:
    type: nuget-feed
    key: "private-feed"
    url: "https://xxx.pkgs.visualstudio.com/aaa/_packaging/private-feed/nuget/v3/index.json"
    token: PAT:${{ AZURE_ACCESS_TOKEN }}
updates:
  - package-ecosystem: "nuget"
    directories: [ '/xxx/YYY/*' ]
    allow:
      - dependency-name: "AAA.Common.Http"
    target-branch: main
    registries:
      - artifacts
    schedule:
      interval: "daily"
    commit-message:
      prefix: "private repo upgrade"
    open-pull-requests-limit: 5
```
   

**Additional context**
I found something similar on internet https://github.com/dependabot/dependabot-core/issues/8003 However it is for group but I only need to use allow. Any idea how can I pass this error?

**Comment by rhyskoedijk** [comment]
@caglanurcetinn thanks for the report.
It looks like you are using version 1 of the task; can you let us know which version of the `dockerImageTag` you have set in your pipeline?

Briefly looking at the stack trace, it looks like the Dependabot metadata stored one of your existing active pull requests is causing problems. It is possible you might be work around this issue by completing/abandoning any other [active] Dependabot PRs that are currently open.

If you are able to confirm which Docker image tag you are using, I will investigate further.

**Comment by caglanurcetinn** [comment]
Thanks for the quick response. It worked when I closed the other open PR. The open PR was related with a different package. Basically, I would expect it to create 2 different PRs as they are not related with same package.

My pipeline is;

```
pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: CheckDependencies
    jobs:
      - job: Dependabot
        displayName: 'Run Dependabot'
        steps:
          - task: dependabot@1
            displayName: 'Detect Outdated Nuget Packages and Create PRs'
            inputs:
              useUpdateScriptvNext: true
            env:
              AZURE_ACCESS_TOKEN: $(System.AccessToken)
```

I could not find the dockerImageTag. How can I find it? And you said I use version1 in task, when I try to use task: dependabot@2, it didnt work. Thanks for help!
