### ISSUE TITLE
401 when calling Identities endpoint

### ISSUE THREAD

**Issue by miszoPandy** [tinglesoftware/dependabot-azure-devops#1499]
**Describe the bug**

Requests to resolve approvers don't work because the WebApi is reused and the PersonalAccessTokenHandler rejects cross domain calls. 

**Categorization**
- [x] This is not a permissions issue (Seek help at https://github.com/tinglesoftware/dependabot-azure-devops/discussions/1245)

We get 401 for the identities endpoint of azure devops. the same token works via postman and also is able to create pr-s via this task. 

**Repository**
URL: e.g. https://dev.azure.com/tingle/dependabot/_git/repro-684

**To Reproduce**

1. Add any reviewers under the `dependabot.yaml` configuration. 
2. Try to run the task
3. The task will fail with an error telling that the authentication failed against the ADO identities API 

**Expected behavior**
The personal access token should work against both the identities and the organization API

**Logs and screenshots**
If applicable, include relevant logs or screenshots to help explain your problem.
See [extension troubleshooting](https://github.com/tinglesoftware/dependabot-azure-devops/blob/main/docs/extension.md#troubleshooting-issues) for more on how to collect additional diagnostic logs.

**Extension (please complete the following information):**
 - Host: Azure DevOps
 - Version 2.x.x+ (latest)

**Server (please complete the following information):**
 - Region [e.g. westeurope]
 - Version 3.x.x+

**Additional context**

The problem problem probably originates from here 

https://github.com/microsoft/typed-rest-client/blob/master/lib/handlers/personalaccesstoken.ts#L19

The origin is never specified so it becomes the host of the first request. Then because this task reuses the webapi client the origin will not match the host and the boolean for allowCrossOriginRequests is also false since it's an optional value and never specified by the task. 
This means the auth header never gets added to the request when calling the identities endpoint here

https://github.com/tinglesoftware/dependabot-azure-devops/blob/a0d7902dd3e970c4668751d56eaa20af2e1e49d0/extension/tasks/dependabotV2/utils/azure-devops/AzureDevOpsWebApiClient.ts#L57

Possible fix: 
Create two webapi clients, one for each host or allow crossdomain calls by enabling it when calling the authtokenhandler.

**Comment by miszoPandy** [comment]
happy to propose the fix once approved.

**Comment by rhyskoedijk** [comment]
@miszoPandy are you able to share the relevent parts of your `dependabot.yml` and task out logs (with `System.Debug = true`). I'm curious to know how you've configured the reviewers/assignee's and what the HTTP request/response looks like as I am not able to reproduce this issue. I am able to resolve identities from username, email, and group without any cross domain errors.

Are you using Azure DevOps (cloud) or Azure DevOps Server (on-prem)?

**Comment by miszoPandy** [comment]
We are using Azure Devops cloud. 

The config looks sometihng like this. 

I don't have time now to further debug this unfortunately

```
version: 2
registries:
  azure-artifacts:
    type: nuget-feed
    key: "feed"
    url: "https://package-path"
    token: PAT:${{ AZURE_ACCESS_TOKEN }}
updates:
  - package-ecosystem: "nuget"
    directories: [ '/folder/*' ]
    allow:
      - dependency-name: "Depy"
    target-branch: main
    registries:
      - azure-artifacts
    schedule:
      interval: "daily"
    commit-message:
      prefix: "version upgrade"
    open-pull-requests-limit: 5
    reviewers:
      - "xyz@ourdomain.net"
```
