### ISSUE TITLE
Configuring experiments as "enable-record-ecosystem-meta=false" in dependabot@2 doesn't prevent associated logs to be displayed

### ISSUE THREAD

**Issue by emmanwl** [tinglesoftware/dependabot-azure-devops#1531]
**Describe the bug**
I run a dependabot@2 (2.40.1110) task and I am setting experiments to disable enable-record-ecosystem-meta by providing 
experiments: 'enable-record-ecosystem-meta=false' as a task input.

In the task log, I still can see errors traces like: 

- cli  |  ***  |  unexpected output type: record_ecosystem_data

- updater | *** | ERROR <job_update_0_npm_and_yarn_all> Failed to record ecosystem meta after 3 retries

I was supposing that disabling this experiment would result in not displaying those lines: the thing is those retries are time consuming from what I see.

Not sure this is a bug but I am missing something obviously.

I have done the same test by providing the V2 task a similar input (but using underscores between words instead of dashes since I found references to both in the documentation): 
experiments: 'enable_record_ecosystem_meta=false'  but it produces the same result.

**Categorization**
- [x] This is not a permissions issue (Seek help at https://github.com/tinglesoftware/dependabot-azure-devops/discussions/1245)

**Repository**
NA

**To Reproduce**
1. Set experiments: 'enable-record-ecosystem-meta=false' as a dependabot@2 task input
2. Run the task, notice that the new experiments value(s) was/were correctly passed into parameter but that the "faulty" log lines remain.

**Expected behavior**
I would expect those log lines not to be displayed (and presumably the underlying retries not to be performed)

**Logs and screenshots**
See [extension troubleshooting](https://github.com/tinglesoftware/dependabot-azure-devops/blob/main/docs/extension.md#troubleshooting-issues) for more on how to collect additional diagnostic logs.

**Extension (please complete the following information):**
 - Host: [Azure DevOps Service]
 - Version [e.g. Dev19.M247.1]

**Additional context**
None.

**Comment by SKoningScanplan** [comment]
Encountering the same issue. PRs are still created but the errors make the ADO pipeline fail.

**Comment by rhyskoedijk** [comment]
@emmanwl  @SKoningScanplan thanks for reporting, could one of you please provide the relevant parts of you `dependabot.yml` for this update, so I can attempt to reproduce. At minimum, I need to know which ecosystem is being used.

**Comment by SKoningScanplan** [comment]
@rhyskoedijk Here you go:
```
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "mlflow*"
      - dependency-name: "numpy"
      - dependency-name: "setuptools"
    groups:
      azure-ml-deps:
        patterns:
          - "azureml-*"
          - "inference-schema"
          - "azure-ai-ml"
    target-branch: "dependabot-collection-branch"
    open-pull-requests-limit: 5
```

**Comment by emmanwl** [comment]
Hello,

here is mine (not same ecosystem as @SKoningScanplan ): 

```yaml
version: 2
updates:
  - package-ecosystem: npm
     directory: "/"
     azureDevopsAccessToken: '$(System.AccessToken)'
     versioning-strategy: 'auto'
     open-pull-requests-limit: 10
     commit-message:
       prefix: "build"
       include: "scope"
     registries:
       - my-corp-npm-registry
registries:
  my-corp-npm-registry:
    type: npm-registry
    url: 'https://some-path/'
    username: some-user-name
    password: some-user-password
```

**Comment by leloscheidt** [comment]
Hello, here is my dependabot.yml file and I got the same issue as @emmanwl , but my pipeline expires in 1hr. No PRs could be created in that time:

```
version: 2
updates:  
  - package-ecosystem: "npm"    
       directory: "/"    
       schedule:      
         interval: "daily"    
      target-branch: "master"  
```

I also tried what was suggested and added the `experiments: 'enable-record-ecosystem-meta=false'` but still the same error.
