### ISSUE TITLE
NuGet private feed not probed

### ISSUE THREAD

**Issue by SeanFeldman** [tinglesoftware/dependabot-azure-devops#1545]
**Describe the bug**

Configuring NuGet private feed on Azure DevOps doesn't appear to be attempted when Dependabot is trying to restore packages from the private NuGet feed. Inspecting logs, shows no indication of the private feed (registry) being attempted. 

**Categorization**
- [x] This is not a permissions issue (Seek help at https://github.com/tinglesoftware/dependabot-azure-devops/discussions/1245)

**Repository**

N/A

**To Reproduce**
1. create the necessary files (below)
1. run AzDO pipeline

**Expected behavior**

1. Packages to be restored from the private feed. 
1. Show that the private feed is probed.

**Logs and screenshots**

[dependabot.log.txt](https://github.com/user-attachments/files/18605045/dependabot.log.txt)

**Extension (please complete the following information):**
 - Host: Azure DevOps

**Additional context**

`depedabot.yml` pipeline

```yml
schedules:
  - cron: "0 0 */7 * *"
    displayName: 'Run Dependabot (once a week)'  
    always: true 
    branches:
      include:
        - master
    batch: true

trigger: none # Disable CI trigger

variables:
  - group: Dependabot

jobs:
  - job: Default
    timeoutInMinutes: 60
    
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:
      - task: dependabot@2
        displayName: 'Run Dependabot'
        inputs:
          useConfigFile: true
          useUpdateScriptvNext: true
          azureDevOpsAccessToken: '$(System.AccessToken)'
        env:
          #PAT: $(System.AccessToken)  # Attempted this as well, didn't work either
          PAT: '$(PAT)'                             # PAT is a variable from the Dependabot variables group
```

`.githut\dependabot.yml`

```yml
version: 2

registries:
  # Azure DevOps private feed
  my-feed:
    type: nuget-feed
    key: "dotnet"
    url: "https://pkgs.dev.azure.com/my/_packaging/MyNuget/nuget/v3/index.json"
    token: PAT:${{ PAT }}

updates:
  - package-ecosystem: "nuget"
    target-branch: master
    directory: /
    registries: 
      - my-feed
    commit-message:
      prefix: "deps"
    schedule:
      interval: weekly
      day: sunday      
    open-pull-requests-limit: 1000
    groups:
      My:
        patterns:
          - 'My.*'
      Microsoft:
        patterns:
          - 'Microsoft.*'
          - 'Azure.*'
      TestLibraries:
        patterns:
          - 'Moq*'
          - 'FakeItEasy*'
          - 'FluentAssertions*'
          - 'xunit*'
          - 'coverlet*'
          - 'Verify*'
          - 'Microsoft.NET.Test.Sdk*'
      ThirdParty:
        patterns:
          - '.*'
```

**Comment by SeanFeldman** [comment]
It looks like I was missing [`replaces-base: true`](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#url-and-replaces-base) in the registration of the registry.

```
registries:
  # Azure DevOps private feed
  my-feed:
    type: nuget-feed
    key: "dotnet"
    url: "https://pkgs.dev.azure.com/my/_packaging/MyNuget/nuget/v3/index.json"
    token: PAT:${{ PAT }}
    replaces-base: true
```

Is it not possible to add a registry in addition to the base registry (NuGet.org) rather than replacing the base one?
