### ISSUE TITLE
Merge config file and pipeline inputs

### ISSUE THREAD

**Issue by gitolicious** [tinglesoftware/dependabot-azure-devops#156]
I would like to set the pull request limit with a pipeline variable. At the same time I need to use a config file as I have some ignored dependencies which are a mess to inject via the pipeline. So here is what I tried:

```yaml
- task: dependabot@1
  inputs:
    useConfigFile: true
    openPullRequestsLimit: $(openPullRequestsLimit)
```

Unfortunately, when using the config file, other inputs are ignored. The reason lies here:

https://github.com/tinglesoftware/dependabot-azure-devops/blob/f041bc6f884333edc11834641fa61441479aa06b/src/extension/task/index.ts#L156-L157

Would it be possible to

1. read the config file
2. read the inputs and
3. merge the two,

probably having the inputs overwrite config file settings if conflicts arise?
