### ISSUE TITLE
The process '/usr/bin/docker' failed with exit code 1

### ISSUE THREAD

**Issue by MoamenMohamed93** [tinglesoftware/dependabot-azure-devops#164]
There seems to be an error during updating the package version.

**Pipeline YAML** 
I am using the same sample from the extension page

```
trigger: none # Disable CI trigger

schedules:
- cron: '0 2 * * *' # daily at 2am UTC
  always: true # run even when there are no code changes
  branches:
    include:
      - master
  batch: true
  displayName: Daily

pool:
  vmImage: 'ubuntu-latest' # requires macos or ubuntu (windows is not supported)

steps:
- task: dependabot@1
  inputs:
    packageManager: 'nuget'
    directory: '/'
    targetBranch: 'master'
    versioningStrategy: 'auto'
```

**Result Log**
```
Status: Downloaded newer image for tingle/dependabot-azure-devops:0.5
warning: parser/current is loading parser/ruby27, which recognizes
warning: 2.7.4-compliant syntax, but you are running 2.7.1.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
/home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.156.9/lib/dependabot/clients/azure.rb:267:in `post': Dependabot::Clients::Azure::Forbidden (Dependabot::Clients::Azure::Forbidden)
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.156.9/lib/dependabot/clients/azure.rb:166:in `create_commit'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.156.9/lib/dependabot/pull_request_creator/azure.rb:66:in `create_commit'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.156.9/lib/dependabot/pull_request_creator/azure.rb:34:in `create'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.156.9/lib/dependabot/pull_request_creator.rb:104:in `create'
	from ./update-script.rb:427:in `block in <main>'
	from ./update-script.rb:272:in `each'
	from ./update-script.rb:272:in `<main>'
Using hostname = 'dev.azure.com', protocol = 'https', port = '443'.
Using 'https://dev.azure.com:443/' as API endpoint
Fetching nuget dependency files for MoamenMohamed0091/MoamenMohamed/_git/DependabotTest
Targeting 'default' branch under '/' directory
Using 'auto' requirements update strategy
Parsing dependencies information
Checking if Newtonsoft.Json 9.0.1 needs updating
Requirements to unlock own
Updating Newtonsoft.Json from 9.0.1 to 13.0.1
[error]The process '/usr/bin/docker' failed with exit code 1
```
