### ISSUE TITLE
PR already exists or an error has occurred.

### ISSUE THREAD

**Issue by SeanFeldman** [tinglesoftware/dependabot-azure-devops#181]
I'm getting the following error and not quite sure what is the problem:

```
Checking if Microsoft.Extensions.Configuration 3.1.18 needs updating
Requirements to unlock own
Updating Microsoft.Extensions.Configuration from 3.1.18 to 5.0.0
Submitting Microsoft.Extensions.Configuration pull request for creation. Failed! PR already exists or an error has occurred.
```

There's no PR, I've validated that.

The pipeline looks as the following:

```yaml
schedules:
  - cron: "0 4 * * 1"
    displayName: 'Weekly Run'
    always: true # run even when there are no code changes
    branches:
      include:
        - master
    batch: true
trigger: none # Disable CI trigger
pool:
  vmImage: 'ubuntu-latest'
steps:
  - task: dependabot@1
    displayName: 'Run Dependabot'
    inputs:
      packageManager: 'nuget'
      openPullRequestsLimit: 10
      versioningStrategy: 'auto'
      setAutoComplete: false
      azureDevOpsAccessToken: '$(System.AccessToken)'
```

Settings wise, `Contribute to pull requests` and `Create branch` are enabled:
![image](https://user-images.githubusercontent.com/1309622/132652873-4eb21ca7-61d8-4ab7-b6b9-9ed1e37b7562.png)
