### ISSUE TITLE
Npm PR created with major version upgrade but patch only is set in package.json

### ISSUE THREAD

**Issue by ray-kay** [tinglesoftware/dependabot-azure-devops#195]
Hi there,

after the first successful pipeline with dependabot it create these 5 PRs

![image](https://user-images.githubusercontent.com/12802386/138449063-dd857fc4-6d7c-4489-8eb9-77d394b7a03a.png)

But in the package.json I have

- "@types/jasmine": "~3.5.0" => so only patch but it would upgrade to a new minor version
- "@angular/cli": "~10.2.0"  =>so only patch but it would upgrade to a new major version

package-lock.json
- "@types/jasmine": {
            "version": "3.5.12",

- "@angular/cli": {
            "version": "10.2.0",

**The expected result would be a version upgrade to** 
- @types/jasmine: 3.5.14
- @angular/cli: 10.2.3

My Pipeline task looks like
```

- task: dependabot@1
  inputs:
    packageManager: 'npm'
    directory: $(npmWorkingDir)
    versioningStrategy: 'auto'
```

on ubuntu-latest with node 14.x

**Comment by mburumaxwell** [comment]
@ray-kay ,

If I get you correctly, the PR was created for 3.5.12 to 3.9.1 instead of 3.5.12 to 3.5.14 for `@types/jasmine`. Correct?
In this case, you need to control package updates using the `.azuredevops/dependabot.yml` file so that major versions are ignored.

Change your pipeline to 
```yaml
- task: dependabot@1
  inputs:
    useConfigFile: true
```

Add a `.azuredevops/dependabot.yml` file with:

```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # Ignore all major updates for sensitive packages
      - dependency-name: "@types/jasmine"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular/cli"
        update-types: ["version-update:semver-major"]
```
For more see https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#ignore
