### ISSUE TITLE
dependabot adds .git to end of private Azure repository url

### ISSUE THREAD

**Issue by jenswegar** [tinglesoftware/dependabot-azure-devops#220]
I have a php/composer project that has a dependency on a private git repository, which is also hosted on Azure repos. It's the same organisation, but different project. I'm using the Dependabot Azure marketplace extension. But for some reason dependabot always fails once it starts to check the dependency from the private repository. I enabled ```EXCON_DEBUG=1``` for debugging the requests and when I looked through the logs I noticed that the private dependency always fails with a 404 not found error. When I look at the URL that dependabot tries to download, I noticed that it has added a ```.git``` to the end of the repository url when it tries to fetch the /info/refs. But this is not a valid Azure repos URL. I tested this by trying to open the URL directly in a browser, which resulted in a 404. If I remove the .git from the end of the repo then the URL works:

```
# this fails to open in browser
https://dev.azure.com/<org-name>/<dependecy-project-name>/_git/reponame.git/info/refs

# this works
https://dev.azure.com/<org-name>/<dependecy-project-name>/_git/reponame/info/refs
```
Nowhere in my project or dependabot config do I have the repository url defined with a .git in the end, so this seems to be something dependabot tacks on somewhere along the way. But just in case I'm missing something in my config I included them below as well.

**dependabot logs for the request to the private repo (redacted)**: https://gist.github.com/jenswegar/2dabf6abad610ed5175fceeb596ddfd8

**.azuredevops/dependabot.yml**:

```
version: 2

updates:
# tried various combinations of package-ecosystem: git, git_source,composer. Same result with all of them, not sure which would actually be correct for a private repo containing a php library.
- package-ecosystem: "composer"
  directory: "src"
  schedule:
    interval: "weekly"
  registries:
  - myprivaterepo # Allow version updates for dependencies in this registry
registries:
  myprivaterepo:
    type: composer-repository
    url: https://dev.azure.com/<org-name-REDACTED>/<project-name-REDACTED>/_git/<repo-name-REDACTED>
    # testing with hard coded credentials just to make sure variable substitutions are not causing the problem
    username: xyz
    password: somelongstring

```

**Azure pipeline definition**:
```
# Runs dependabot against the project to detect old versions of dependencies

trigger:
- develop

variables:
  dependabotImage: tingle/dependabot-azure-devops:0.5

pool:
  vmImage: 'ubuntu-latest' 

steps:

# Cache the docker image download to save time and network requests on next build
- task: Cache@2
  inputs:
    key: docker | "${{ variables.dependabotImage }}"
    path: $(Pipeline.Workspace)/docker
    cacheHitVar: DOCKER_CACHE_HIT
  displayName: Cache Docker dependabot image

- script: |
    docker load -i $(Pipeline.Workspace)/docker/cache.tar
  displayName: Restore Docker dependabot image
  condition: and(not(canceled()), eq(variables.DOCKER_CACHE_HIT, 'true'))

- script: |
    mkdir -p $(Pipeline.Workspace)/docker
    docker pull ${{ variables.dependabotImage }}
    docker save -o $(Pipeline.Workspace)/docker/cache.tar ${{ variables.dependabotImage }}
  displayName: Pull and save dependabot image
  condition: and(not(canceled()), or(failed(), ne(variables.DOCKER_CACHE_HIT, 'true')))

- task: dependabot@1
  inputs:
    useConfigFile: true
    extraEnvironmentVariables: 'EXCON_DEBUG=1'

```

composer.json definition of repository:
```
{
  ...
  "repositories": [
    ...
    {
      "url": "https://dev.azure.com/<org-name-REDACTED>/<project-name-REDACTED>/_git/<repo-name-REDACTED>",
      "type": "git"
    },
    ...
  ],
```
