### ISSUE TITLE
Mask azureDevOpsAccessToken

### ISSUE THREAD

**Issue by nitindasnit** [tinglesoftware/dependabot-azure-devops#235]
Hi,

I want to know how can i mask "azureDevOpsAccessToken" while using Dependabot task in my pipeline.
Tried using as variable  , shown below but no luck.
Please let me know how can i mask this.
steps:
      
      - task: dependabot@1
        inputs:
          useConfigFile: true
         azureDevOpsAccessToken: '$token'
          targetRepositoryName: 'depbotPoc'
        displayName: Run dependabot

**Comment by mburumaxwell** [comment]
Hi @nitindasnit 

To use the token as a variable (not equivalent to masking), try the following:
```yaml
steps:
- task: dependabot@1
  displayName: Run dependabot
  inputs:
    useConfigFile: true
    azureDevOpsAccessToken: '$(token)'
    targetRepositoryName: 'depbotPoc'
```

Then add `token` as a variable in your pipeline
