### ISSUE TITLE
Dependency Limit Feature

### ISSUE THREAD

**Issue by OneCyrus** [tinglesoftware/dependabot-azure-devops#28]
great work with this extension! any chance we get some more advanced options to limit the dependencies?

e.g.
- limit semver to minor and patch and exclude major release
- allow to include or exclude specific dependency names with wildcards. e.g. Microsoft.*

**Comment by mburumaxwell** [comment]
As per the GitHub native version, these could be achieved with [allow](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#allow), and [limit](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#ignore), with some minor modifications. The only issue is they are both arrays and Azure Pipelines [task schema](https://raw.githubusercontent.com/Microsoft/azure-pipelines-task-lib/master/tasks.schema.json) does not show support for arrays on input types. The most probable option is to work with a configuration file set up in the repository, as described for the [hosted version](https://github.com/tinglesoftware/dependabot-azure-devops#hosted-version). Would this work for you?

**Comment by OneCyrus** [comment]
that sounds exactly what I'm looking for. just to clarify, the support for `.azuredevops/dependabot.yml` with this extension is not available right now but is something you have in mind?

**Comment by mburumaxwell** [comment]
Correct the extension does not currently offer support for the file primarily due to the use of arrays and also because we cannot use build agents to queue a build in the future based on the time set in the file. To solve that, we have to work with an app hosted on Kubernetes. You can see something similar for GitLab [here](https://gitlab.com/dependabot-gitlab/dependabot).
We are already doing something similar in our Azure DevOps organization.

As a workaround, to keep using the extension as is and without the `.azuredevops/dependabot.yml` file, you will be able to create a pipeline and specify the conditions via global variables, in the next release. An example:
```yaml
trigger: none # Disable CI trigger

schedules:
- cron: '0 2 0 0 0' # daily at 2am UTC
  always: true # run even when there are no code changes
  branches:
    include:
      - master
  batch: true
  displayName: Daily

# variables declared below can be put in one or more Variable Groups for sharing across pipelines
variables:
  DEPENDABOT_DOCKER_IMAGE_TAG: '0.1.3' # could also be 'latest'
  DEPENDABOT_EXTRA_CREDENTIALS: '[{\"type\":\"npm_registry\",\"token\":\"<redacted>\",\"registry\":\"npm.fontawesome.com\"}]' # put the credentials for private registries and feeds
  DEPENDABOT_ALLOW: '[{\"name\":"django*",\"type\":\"direct\"}]' # packages allowed to be updated
  DEPENDABOT_IGNORE: '[{\"name\":\"express\",\"versions\":[\"4.x\",\"5.x\"]}]' # packages to be ignored

pool:
  vmImage: 'ubuntu-latest' # requires macos or ubuntu (windows is not supported)

steps:
- task: dependabot@1
  inputs:
    packageManager: 'docker'
    directory: '/'
    openPullRequestsLimit: 5
    versioningStrategy: 'auto'
```
