### ISSUE TITLE
Azure extension fails with Pub package manager (Unexpected requirements_update_strategy)

### ISSUE THREAD

**Issue by ko16a46** [tinglesoftware/dependabot-azure-devops#297]
Hello!

I'm trying to use this Azure extension for my Flutter project but it's failing with the error: `/home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-pub-0.192.1/lib/dependabot/pub/update_checker.rb:109:in 'resolve_requirements_update_strategy': Unexpected requirements_update_strategy bump_versions (RuntimeError)`

See error logs for your reference:

```
Starting: Run dependabot
==============================================================================
Task         : Dependabot
Description  : Automatically update dependencies and vulnerabilities in your code
Version      : 1.7.211
Author       : Tingle Software
Help         : For help please visit https://github.com/tinglesoftware/dependabot-azure-devops
==============================================================================
/usr/bin/docker run --rm -i -e DEPENDABOT_PACKAGE_MANAGER=pub (... other env variables)
Unable to find image 'tingle/dependabot-azure-devops:0.7' locally
0.7: Pulling from tingle/dependabot-azure-devops
d5fd17ec1767: Pulling fs layer
f0a6dc030567: Pulling fs layer
0cb2a21c0048: Pulling fs layer
... other Docker stuff ...
c2e9e43f6f8e: Pull complete
41dc914a846d: Pull complete
d7e2ea91a589: Pull complete
d05af08390a7: Pull complete
Digest: sha256:f29bb3b2a8f37470885faef1c46d8416fad9ad720fcc922f87d1b97d1f72fa2c
Status: Downloaded newer image for tingle/dependabot-azure-devops:0.7
warning: parser/current is loading parser/ruby27, which recognizes2.7.6-compliant syntax, but you are running 2.7.5.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Using hostname = 'dev.azure.com', protocol = 'https', port = '443'.
Using '[https://dev.azure.com:443/'](https://dev.azure.com/') as API endpoint
Fetching pub dependency files for [REDACTED]
Targeting 'default' branch under '/packages/flutter_oauth' directory
Using 'bump_versions' requirements update strategy
Parsing dependencies information
Checking if build_runner 2.1.11 needs updating
/home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-pub-0.192.1/lib/dependabot/pub/update_checker.rb:109:in `resolve_requirements_update_strategy': Unexpected requirements_update_strategy bump_versions (RuntimeError)
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-pub-0.192.1/lib/dependabot/pub/update_checker.rb:105:in `resolved_requirements_update_strategy'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-pub-0.192.1/lib/dependabot/pub/update_checker.rb:43:in `updated_requirements'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.192.1/lib/dependabot/update_checkers/base.rb:266:in `preferred_version_resolvable_with_unlock?'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.192.1/lib/dependabot/update_checkers/base.rb:249:in `numeric_version_can_update?'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.192.1/lib/dependabot/update_checkers/base.rb:199:in `version_can_update?'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.192.1/lib/dependabot/update_checkers/base.rb:44:in `can_update?'
	from ./update-script.rb:305:in `block in <main>'
	from ./update-script.rb:273:in `each'
	from ./update-script.rb:273:in `<main>'
No update needed for build_runner 2.1.11
Checking if clock 1.1.0 needs updating
##[error]The process '/usr/bin/docker' failed with exit code 1
Finishing: Run dependabot
```

I think the issue is that the `UpdateChecker` for `pub` expects the `requirements_update_strategy` to be a string only (see [dependabot-core code here](https://github.com/dependabot/dependabot-core/blob/a5d61cc3604118268ea8ed8df6a96170e7297222/pub/lib/dependabot/pub/update_checker.rb#L109) where it crashes), but the `requirements_update_strategy` in this extension is passing in a symbol ([seen here](https://github.com/tinglesoftware/dependabot-azure-devops/blob/47e9574ac679461be6eac1690566589654f2c071/src/script/update-script.rb#L139)). Am I on the right track?

Should the fix be in this project, or in dependabot-core? Note that the `dry-run.rb` script in dependabot-core uses strings only and it works fine ([seen here](https://github.com/dependabot/dependabot-core/blob/a5d61cc3604118268ea8ed8df6a96170e7297222/bin/dry-run.rb#L200)).

----

My `dependabot-pipeline.yml`, for your reference:

```
trigger: none

schedules:
- cron: '0 9 * * *' # daily at 9am UTC / 4am CST
  always: true
  branches:
    include:
      - main
  batch: true
  displayName: Daily

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Dependabot
  displayName: 'Dependabot'

  variables:
    DEPENDABOT_EXTRA_CREDENTIALS: '[{"type": "git_source", "host": "dev.azure.com", "username": "$(ProjectUsername)", "password": "$(System.AccessToken)"}]'

  steps:
  - task: dependabot@1
    displayName: 'Run dependabot'
    inputs:
      packageManager: 'pub'
      versioningStrategy: 'increase'
```
