### ISSUE TITLE
Terraform modules in Azure Devops repos

### ISSUE THREAD

**Issue by AurimasNav** [tinglesoftware/dependabot-azure-devops#308]
Can't figure out a way to make it work for my terraform when I have terraform modules in Azure Repos 

```
  :host          => "dev.azure.com"
  :local_address => "redacted"
  :local_port    => 45288
  :path          => "/<org>/<project>/_git/az-application-insights.git/info/refs"
  :port          => 443
  :reason_phrase => "Not Found"
  :remote_ip     => "13.107.42.20"
  :status        => 404
  :status_line   => "HTTP/1.1 404 Not Found\r\n"
Checking if app_insights::git_provider::repo_name/git_repo(758284703d54a9cb9c82fc911cbaea3cba3c7f2d)::1.0.1 1.0.1 needs updating
/home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.196.0/lib/dependabot/git_metadata_fetcher.rb:58:in `fetch_upload_pack_for': The following git URLs could not be retrieved: https://dev.azure.com/<org>/<project>/_git/az-application-insights (Dependabot::GitDependenciesNotReachable)
```

I've tried to add 
```yml
variables:
- group: dependabot
- name: DEPENDABOT_EXTRA_CREDENTIALS
  value: '[{"type":"terraform_registry", "url":"https://dev.azure.com", "token":"$(PAT)"}, {"type":"git", "url":"https://dev.azure.com", "username":"x-access-token", "password":"$(PAT)"}]'
```
to no avail.

In the browser I get `not found` error for the path `/<org>/<project>/_git/az-application-insights.git/info/refs` however it works if I remove the `.git` part from path.
