### ISSUE TITLE
labels declared in dependabot.yml file are not used in Pull-Request

### ISSUE THREAD

**Issue by schamal2205** [tinglesoftware/dependabot-azure-devops#317]
I have a dependabot.yml-file which looks like this: 
```yaml
version: 2
updates:
 - package-ecosystem: nuget
   directory: "/"
   version-strategy: auto
   target-branch: master
   ignore:
     - dependency-name: "*"
       update-types: ["version-update:semver-major", "version-update:semver-patch"]
   labels:
     - "AutoCompleteWI"
 ```
but the created Pull-Request does not contain the label `AutoCompleteWI`
![image](https://user-images.githubusercontent.com/37846690/180966295-182aa39a-80b0-439e-ae99-22065a0d10f6.png)

**Comment by sebastiansterk** [comment]
Having the exact same issue here. My pipeline task:
```
- task: dependabot@1
  inputs:
    useConfigFile: true
    gitHubAccessToken: $(GITHUB_PAT)
```
My .azuredevpops/dependabot.yml:
```
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
    labels:
      - "test"
      - "dependencies"
```
