### ISSUE TITLE
Migration from explicit inputs to configuration file unclear

### ISSUE THREAD

**Issue by chasewallis** [tinglesoftware/dependabot-azure-devops#327]
This morning I noticed a warning about explicit inputs being deprecated. I went to work to migrate to a configuration file, but I'm not sure how to accomplish it. I am using azure devops pipeline and have the following pipeline:

```
schedules:
- cron: '0 7 8-15 * 3'
  always: true # run even when there are no code changes
  branches:
    include:
      - dev
  batch: true
  displayName: Weekly

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: dependabot@1
  inputs:
    packageManager: 'nuget'
    azureDevOpsAccessToken: $(Feed-Token)
    targetBranch: 'dev'
    openPullRequestsLimit: 15
    setAutoComplete: true
```

This runs on the 2nd wednesday of every month. To convert it to the config file, I think I just remove the inputs so it will be something like:
```
schedules:
- cron: '0 7 8-15 * 3'
  always: true # run even when there are no code changes
  branches:
    include:
      - dev
  batch: true
  displayName: Weekly

pool:
  vmImage: 'ubuntu-latest' 

steps:
- task: dependabot@1
  inputs:
    useConfigFile: true
```

And now I need to add a `.azuredevops/dependabot/yml` like this:
```
version: 2
updates:
  - package-ecosystem: "nuget" 
    directory: "/" 
    schedule:
      interval: "weekly"
      time: "02:00"
      day: "wednesday"
    target-branch: dev
    open-pull-requests-limit: 15
```

 I looked in the [official spec](https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates) as recommended, but I'm not seeing options for `setAutoComplete` or `azureDevOpsAccessToken`, so I'm unsure on how to still use those features.

The official spec requires a schedule.interval, but that is handled by the azure pipeline. Unless I am misunderstanding something, I don't see how the schedule in the `.azuredevops/dependabot/yml` would trigger the pipeline. So it seems I would just put a dummy schedule there as it is required?

Finally the [documentation](https://github.com/tinglesoftware/dependabot-azure-devops/blob/main/src/extension/README.md#usage) still recommends the use of explicit inputs, so any user just setting up their pipeline will set it up in a deprecated way.

**Comment by venerik** [comment]
I discovered that the inputs that are part of the official spec must be moved to the config file. All other inputs stay in the task.

In my case this task

``` yaml
- task: dependabot@1
  inputs:
    packageManager: 'nuget'
    versioningStrategy: 'increase'
    openPullRequestsLimit: 5
    failOnException: true
    milestone: '7202'
    azureDevOpsAccessToken: '$(PAT)'
    extraEnvironmentVariables: 'EXCON_DEBUG=1;DEPENDABOT_EXTRA_CREDENTIALS=[{"type":"nuget_feed","url":"https://pkgs.dev.azure.com/xxx/nuget/v3/index.json","token":":$(PAT)"}]'
```

became this task

``` yaml
- task: dependabot@1
  inputs:
    useConfigFile: true
    azureDevOpsAccessToken: '$(PAT)'
    extraEnvironmentVariables: 'EXCON_DEBUG=1;DEPENDABOT_EXTRA_CREDENTIALS=[{"type":"nuget_feed","url":"https://pkgs.dev.azure.com/xxx/nuget/v3/index.json","token":":$(PAT)"}]'
```

with this dependabot.yml in the .\azuredevops folder

``` yaml
version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    open-pull-requests-limit: 5
    versioning-strategy: "increase"
    milestone: '7202'
```
