### ISSUE TITLE
Dependabot doesn't work for maven, because of spring.io/status HTTP 404 Not found error

### ISSUE THREAD

**Issue by Wincioor11** [tinglesoftware/dependabot-azure-devops#345]
Dependabot doesn't work for maven, because of spring.io/status HTTP 404 Not found error

```
trigger: none

stages:
  - stage: CheckDependencies
    displayName: 'Check Dependencies'
    jobs:
      - job: Dependabot
        displayName: 'Run Dependabot'
        pool: 
          name: Linux
          vmImage: ubuntu-latest
        steps:
          - task: dependabot@1
            displayName: 'Run Dependabot - gradle'
            inputs:
              packageManager: gradle
              directory: /
              targetBranch: develop
              openPullRequestsLimit: 10
              versioningStrategy: 'auto'
              extraEnvironmentVariables: 'EXCON_DEBUG=1'
```

Error:
```:host          => "spring.io"
  :local_address => "172.17.0.2"
  :local_port    => 36872
  :path          => "/status"
  :port          => 443
  :reason_phrase => "Not Found"
  :remote_ip     => "104.20.5.247"
  :status        => 404
  :status_line   => "HTTP/1.1 404 Not Found\r\n"
```

And it seriously doesn't exist...
![obraz](https://user-images.githubusercontent.com/38164733/190384918-8d8836cd-417d-4607-a0da-72c39a667cae.png)

How can I replaced/overwrite the URL? I think the "https://status.spring.io/" is the correct one.
