### ISSUE TITLE
package with high severity vulnerability not detected as vulnerable

### ISSUE THREAD

**Issue by pluservice** [tinglesoftware/dependabot-azure-devops#360]
We are evaluating dependabot-azure-devops on a .net 6 test solution which includes the vulnerable package Newtonsoft.Json 12.0.3 (see https://github.com/advisories/GHSA-5crp-9r3c-p9vr)

In order to check this extention's behavior with vulnerabilites, we have followed [these instructions](https://github.com/tinglesoftware/dependabot-azure-devops/issues/161#issuecomment-986813568) which are coherent with the code: https://github.com/tinglesoftware/dependabot-azure-devops/blob/928d35912a33364e52ca3c65141225162de4b2a4/src/script/update-script.rb#L352

**Expected behaviour:** The plugin should open a PR to update the vulnerable package 

**Actual behaviour:** No PR opened, as if `checker.vulnerable==false` see log:
```
/usr/bin/docker run --rm -i -e DEPENDABOT_PACKAGE_MANAGER=nuget -e DEPENDABOT_FAIL_ON_EXCEPTION=true -e DEPENDABOT_EXCLUDE_REQUIREMENTS_TO_UNLOCK= -e AZURE_PROTOCOL=https -e AZURE_HOSTNAME=devops.superdriver.it -e AZURE_ORGANIZATION=DefaultCollection -e AZURE_PROJECT=met -e AZURE_REPOSITORY=supersecure-api -e AZURE_ACCESS_TOKEN=*** -e AZURE_SET_AUTO_COMPLETE=false -e AZURE_MERGE_STRATEGY=2 -e DEPENDABOT_VERSIONING_STRATEGY=auto -e DEPENDABOT_ALLOW_CONDITIONS=[{"dependency-name":"a1","dependency-type":"all"}] -e AZURE_AUTO_APPROVE_PR=false tingle/dependabot-azure-devops:0.7
..
..
Checking if Newtonsoft.Json 12.0.3 needs updating
Requirements to unlock own
Updating Newtonsoft.Json is not allowed
```

**Comment by mburumaxwell** [comment]
@pluservice security only updates are not yet supported in this extension. You have linked the correct issue: #161

That said I do expect that the package would be updated unless there's more to it than you have indicated. Could you share the configuration yaml and the pipeline yaml in full?

**Comment by pluservice** [comment]
This is our simple pipeline  yaml,  as you can see we don't use the configuration file right now
thanks

```
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: DevSecOps
  demands: Agent.OS -equals Linux

variables:
  PAT: $(System.AccessToken)
  # 
  DEPENDABOT_ALLOW_CONDITIONS: '[{"dependency-name":"a1","dependency-type":"all"}]'


steps:

- task: dependabot@1
  inputs:
    packageManager: 'nuget'
    versioningStrategy: 'auto'
    openPullRequestsLimit: 0
    dockerImageRepository: 'tingle/dependabot-azure-devops'
    azureDevOpsAccessToken: $(PAT)

```
