### ISSUE TITLE
Support for helm

### ISSUE THREAD

**Issue by nilekhc** [tinglesoftware/dependabot-azure-devops#366]
Hey @mburumaxwell,
Recently, we have added support for helm in dependabot core. https://github.com/dependabot/dependabot-core/pull/5738

Do we need a new release of the docker image here?

**Comment by mburumaxwell** [comment]
Hi @nilekhc , yes a new release of the docker image is required but after there's a new release of the `depenedabot-core` package.  The last one was over a month ago, but I see you are already ahead of game: https://github.com/dependabot/dependabot-core/pull/5738#issuecomment-1275425261.

**Comment by nilekhc** [comment]
@mburumaxwell, does the latest tag of tingle/dependabot-azure-devops pull main branch of `dependabot-core`?

**Comment by mburumaxwell** [comment]
@nilekhc no it doesn't because this repository uses the gem packages that have been released. I am unsure of the stability in supporting "nightly" versions of dependabot-core

**Comment by nilekhc** [comment]
@mburumaxwell Looks like dependabot core has changed its release model. 

https://github.com/dependabot/dependabot-core/pull/5738#issuecomment-1290111754

**Comment by nilekhc** [comment]
@mburumaxwell Looks like they have released a new version - https://github.com/dependabot/dependabot-core/pull/5738#issuecomment-1297377878

**Comment by nilekhc** [comment]
@mburumaxwell Any luck with new release of the extension?

**Comment by mburumaxwell** [comment]
@nilekhc quite a number of changes I needed to go through to see if there is anything that's an issue. A new version should be available later in a few hours.

**Comment by nilekhc** [comment]
@mburumaxwell any luck?

**Comment by mburumaxwell** [comment]
@nilekhc , the release on 7th November has the updated dependabot libraries. Does this fail on your setup?

**Comment by mburumaxwell** [comment]
@nilekhc , experiments and other updater options can now be specified in an ENV or in the task e.g. `goprivate=true,kubernetes_updates=true` as per #391.

Does this and the updated base packages (Nov 7) resolve the issue, now?

**Comment by nilekhc** [comment]
Hi @mburumaxwell,
It work's for Dcokerfile and Kubernetes YAML files. But it's not working for Helm chart values.yaml file.

I am now pulling `tingle/dependabot-azure-devops:0.10` in my pipeline and using the config file as follows:

```yaml
jobs:
  - job:
    steps:
    - task: dependabot@1
      inputs:
        useConfigFile: true
```

The config file looks like this:
```yaml
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    assignees:
      - "dependabot"
```

Test helm chart has values.yaml file which contains:
```yaml
image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.17.7"
```

I am expecting it to create PR for `tag` with the latest version. Is there anything I am missing here?

**Comment by mburumaxwell** [comment]
I'm not sure about the functionality specific for Helm vs Docker/Kubernetes. Could it be that a second nesting level is required, similar to the examples in https://github.com/dependabot/dependabot-core/pull/5738

Say

```yaml
controller:
  image:
    repository: nginx
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.17.7"

```
