### ISSUE TITLE
No commit-message prefix is being set

### ISSUE THREAD

**Issue by sebastiansterk** [tinglesoftware/dependabot-azure-devops#410]
### Setup
I'm using the Azure DevOps extension 0.11.2.300 (Latest) and I run an azure devops pipeline which executes the dependabot task

.github/dependabot.yaml
```
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: "chore"
    labels:
      - "skip"
      - "dependencies"
  - package-ecosystem: "docker"
    directory: "/"
    commit-message:
      prefix: "chore"
    labels:
      - "skip"
      - "dependencies"
```

azure-pipelines.yaml
```
trigger: none

pool:
  name: "Local Pipeline Agent"
  
steps:
- task: dependabot@1
  inputs:
    useConfigFile: true
```

The pipeline task creates the following docker container run command: `/usr/bin/docker run --rm -i -e DEPENDABOT_PACKAGE_MANAGER=npm -e DEPENDABOT_FAIL_ON_EXCEPTION=true -e DEPENDABOT_REJECT_EXTERNAL_CODE=false -e DEPENDABOT_EXCLUDE_REQUIREMENTS_TO_UNLOCK= -e AZURE_PROTOCOL=https -e AZURE_HOSTNAME=dev.azure.com -e AZURE_ORGANIZATION=xxxMyOrgxxx -e AZURE_PROJECT=xxxMyProjectxxx -e AZURE_REPOSITORY=xxxMyRepoxxx -e AZURE_ACCESS_TOKEN=*** -e AZURE_SET_AUTO_COMPLETE=false -e AZURE_AUTO_COMPLETE_IGNORE_CONFIG_IDS=[] -e AZURE_MERGE_STRATEGY=2 -e DEPENDABOT_DIRECTORY=/ -e DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=5 -e DEPENDABOT_LABELS=["skip","dependencies"] -e DEPENDABOT_EXTRA_CREDENTIALS=[] -e AZURE_AUTO_APPROVE_PR=false tingle/dependabot-azure-devops:0.11
`
### Actual behavior
The created PRs are having the following title: `Bump node from 16.14.2-bullseye-slim to 19.2.0-bullseye-slim`
The created PRs are having the following labels: `dependencies`

### Expected behavior
The created PRs are having the following title: `chore: Bump node from 16.14.2-bullseye-slim to 19.2.0-bullseye-slim`
The created PRs are having the following labels: `dependencies`, `skip`

### Additional information
Looks like that the issues #349 and #317 are not yet fixed. If I'm doing something wrong please let me know. Thank you very much.
