### ISSUE TITLE
Dependabot yml config ignore (pip) doesn't work

### ISSUE THREAD

**Issue by nicolasli1** [tinglesoftware/dependabot-azure-devops#454]
when I try to use the configuration file `/.github/dependabot.yml` the conditions to ignore are not working

**To Reproduce**
dependabot.yml file
```

version: 2

updates:

  - package-ecosystem: "pip"
    directory: '/'
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
    versioningStrategy: 'auto'

    ignore:
      - dependency-name: 'autoflake'
      - dependency-name: 'mypy' 
      - dependency-name: 'aws-cdk-lib'
      - dependency-name: 'aws-cdk.aws-glue-alpha'
      - dependency-name: 'aws-cdk.aws-redshift-alpha'
```
run the azure devops pipeline 

```
trigger: none

schedules:
- cron: "00 02 * * *"
  displayName: Daily Check
  branches:
    include:
    - master
  always: true

pool:
  vmImage: ubuntu-latest

steps:

- task: dependabot@1
  inputs:
    useConfigFile: true
    azureDevOpsAccessToken: '$(PAT)'
    dockerImageRepository: 'tingle/dependabot-azure-devops'
    extraEnvironmentVariables: 'DEPENDABOT_DIRECTORY=/infra/requirements'
```
on to the docker container

```
/usr/bin/docker run --rm -i -e DEPENDABOT_PACKAGE_MANAGER=pip -e DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=3 -e DEPENDABOT_DIRECTORY=/ -e DEPENDABOT_FAIL_ON_EXCEPTION=true -e DEPENDABOT_CLOSE_PULL_REQUESTS=true -e AZURE_ORGANIZATION=***  -e AZURE_PROJECT=*** -e AZURE_REPOSITORY=*** -e AZURE_ACCESS_TOKEN=*** -e AZURE_MERGE_STRATEGY=squash -e DEPENDABOT_DIRECTORY=/infra/requirements tingle/dependabot-azure-devops:0.13
Unable to find image 'tingle/dependabot-azure-devops:0.13' locally
0.13: Pulling from tingle/dependabot-azure-devops

```

I was using the same configuration previously and the command to ignore dependencies worked, since the update Respect ignore from config (#401) it works wrong, I would like to know if I am making a mistake.

Environment:

Pipeline builder: Azure Devops Pipelines

Regarts.
