### ISSUE TITLE
dependabot.yml ignored versions are still updated

### ISSUE THREAD

**Issue by DevDavido** [tinglesoftware/dependabot-azure-devops#476]
Hello,
ignored dependencies in the dependbot.yml are completely ignored and PRs are still created.
Azure Pipeline:
```yml
# ...
steps:
  - task: dependabot@1
    displayName: 'Scheduled Dependabot Update'
    inputs:
      dockerImageTag: 0.14.0
      azureDevOpsAccessToken: 'THE_DEPENDABOT_ADO_PAT'
      gitHubConnection: 'THE_DEPENDABOT_GITHUB_SERVICE_CONNECTION'
      extraEnvironmentVariables: DEPENDABOT_AUTHOR_NAME=dependabot; DEPENDABOT_AUTHOR_EMAIL=dependabot@abc.com
```

dependabot.yml with ignored `ch.qos.logback:logback-classic`, but PR with minor update for it is still created:
```yml
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "versions"
    target-branch: "dependabot/develop"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
      - "dependabot"
    ignore:
      # Ignore all major and patch updates for now
      - dependency-name: "*"
        update-types: [ "version-update:semver-major", "version-update:semver-patch" ]
      # Ignore list
      - dependency-name: "ch.qos.logback:logback-classic"
```
Would it be also possible to print the ignored versions to the output?

Edit:
Changing the `update-types` to `[ "version-update:semver-major", "version-update:semver-minor" ]` seems to be ignored completely too. Minor update PR gets still created.

Also tried to use ENV `DEPENDABOT_IGNORE_CONDITIONS` to set the ignore conditions like this, also same result as before:
`extraEnvironmentVariables: DEPENDABOT_AUTHOR_NAME=dependabot; DEPENDABOT_AUTHOR_EMAIL=dependabot@abc.com; DEPENDABOT_IGNORE_CONDITIONS='[{"dependency-name":"ch.qos.logback:logback-classic"}]'`
