### ISSUE TITLE
[🚧] Dependabot 0.14 problem with credentials for private nuget feed in azure devops pipeline

### ISSUE THREAD

**Issue by jakubtrebacz-dev** [tinglesoftware/dependabot-azure-devops#481]
Hi guys,

Can someone assist me with getting this into a dependabot.yml file?
This is my current dependabot setup in pipeline 
```yaml
- task: dependabot@1
  displayName: 'Run Dependabot'
  inputs:
    packageManager: 'nuget'
    directory: '$(Dependabot.Directory)'
    openPullRequestsLimit: '$(Dependabot.OpenPullRequestsLimit)'
    milestone: $(Dependabot.Milestone)
    setAutoComplete: true
    mergeStrategy: '1'
    gitHubAccessToken: '$(Dependabot.GitHubAccessToken)'
    azureDevOpsAccessToken: '$(System.AccessToken)'
    targetRepositoryName: '${{ variables.Repository }}'
    extraEnvironmentVariables: 'DEPENDABOT_EXTRA_CREDENTIALS=[{"type":"nuget_feed","token":"$(VSS_NUGET_ACCESSTOKEN)","url":"https://pkgs.dev.azure.com/$(org)/$(project)/_packaging/$(feed)/nuget/v3/index.json"}]'
```
It took me hours to get this setup and now it is no longer supported by latest release.
The problem I got with `./github/dependabot.yml` file is that I need to declare variables inside of that file that are available in the pipeline like the `"token":"$(VSS_NUGET_ACCESSTOKEN)"` 

I know that the task in pipeline now has to be something like this, with no inputs...
```yaml
- task: dependabot@1
  displayName: 'Run Dependabot'
```
I tried it few times and nothing works at the moment.
Can you provide me with a working example of the `./github/dependabot.yml` file for this scenario, please? 
(with pipeline variables inside that file that work fine, and don't tell me that now I need extra powershell to construct the damn config file)
Also, is there a way to force this task `dependabot@1` to use specific version of the `tinglesoftware/dependabot-azure-devops`? It seems to pick the latest on it's own.
Cheers!

**Comment by mburumaxwell** [comment]
@jakubtrebacz-dev Apologies for the extra work. The rate of change in the functionality has had to evolve at a high rate for the sake of a "brighter future".

You do not have to pass the `DEPENDABOT_EXTRA_CREDENTIALS` variable because the task creates one for you unless you have extra modifications you want to do there. Also, not everything moved from the inputs to the configuration file. Just the ones that were duplicated. This means that the configuration file used for the GitHub hosted version can also be used here without much changes.

Your pipeline becomes:

```yml
- task: dependabot@1
  displayName: 'Run Dependabot'
  inputs:
    setAutoComplete: true # false by default
    mergeStrategy: 'squash' # options: noFastForward, rebase, rebaseMerge or squash
    gitHubAccessToken: '$(Dependabot.GitHubAccessToken)'
    azureDevOpsAccessToken: '$(System.AccessToken)'
    targetRepositoryName: '${{ variables.Repository }}'
```

Your configuration file becomes:

```yaml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: "nuget" # See documentation for possible values
  directory: "/" # Location of package manifests
  schedule:
    interval: "daily"
    time: "02:00"
  milestone: 109 # work item identifier
registries:
  custom-feed-1:
    type: nuget-feed
    url: https://pkgs.dev.azure.com/Contoso/DefaultCollection/_packaging/FirstFeed/nuget/v3/index.json
    token: ':${{VSS_NUGET_ACCESSTOKEN}}'
```

> Only the username, password, token can be replaced with values from the pipeline. Other complex modifications are not encouraged because even though they would works, you may have lots of maintenance works to do with every release.

The task will pick pull a docker image that matches its major and minor version. Here's an example to specify an different version of the docker container:

```yml
- task: dependabot@1
  displayName: 'Run Dependabot'
  inputs:
    dockerImageTag: 0.13.2
```

Notes:
1. Using an older docker image version with a new task version can be problematic as they are updated and built to work together.
2. Images older than 3 months or from CI-builds (e.g. 0.13.3-ci.19) are not guaranteed to be available from the registry.

LMK if this works for you.

**Comment by Rutix** [comment]
Hi,

I am also struggling with this. I tried several things but basically, the setup that I want is the following:

I have an `azure-devops.yml` which looks like this:
```YAML
trigger: none # Disable CI trigger

schedules:
  - cron: "0 2 * * *" # daily at 2am UTC
    always: true # run even when there are no code changes
    branches:
      include:
        - master
    batch: true
    displayName: Daily

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: dependabot

steps:
  - template: dependabot.yml
    parameters:
      repositories:
        [
          ..... REDACTED .....
        ]
      azureDevOpsAccessToken: $(azureDevOpsAccessToken)
      githubAccessToken: $(githubAccessToken)
```

The template looks like this:

```YAML
parameters:
  - name: repositories
    type: object
    default: []
  - name: azureDevOpsAccessToken
    type: string
    default: ''
  - name: githubAccessToken
    type: string
    default: ''

steps:
- script: echo $(azureDevOpsAccessToken)

- ${{ each repo in parameters.repositories }}:
  - task: dependabot@1
    displayName: ${{ repo }}
    inputs:
      azureDevOpsAccessToken: ${{ parameters.azureDevOpsAccessToken }} 
      targetRepositoryName: ${{ repo }}
      gitHubAccessToken: ${{ parameters.githubAccessToken }}
```

An example of a config is the following:

```YAML
version: 2
registries:
  nuget-azure-devops:
    type: "nuget-feed"
    url: "https://pkgs.dev.azure.com/redacted/_packaging/redacted/nuget/v3/index.json"
    password: "PAT:${{azureDevOpsAccessToken}}"
updates:
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "daily"
    milestone: 48085
```

But I am receiving the error:
/home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-nuget-0.215.0/lib/dependabot/nuget/update_checker/repository_finder.rb:117:in `check_repo_response': The following source could not be reached as it requires authentication (and any provided details were invalid or lacked the required permissions): https://pkgs.dev.azure.com/redacted/_packaging/redacted/nuget/v3/index.json (Dependabot::PrivateSourceAuthenticationFailure)

I first thought it might be the template screwing things up but that's not the case. I also tested by adding the dependabot step to the `azure-pipelines.yml` and commenting out the template.

The variable is marked as secret in the `dependabot` variable group. Do you have any suggestions I can make to find out where the problem is? I guess there is no easy way to debug the task because I saw it executes this: 
https://github.com/tinglesoftware/dependabot-azure-devops/blob/b0eaf7f53e49f4498387b39ec1611fa029f855d0/extension/task/utils/convertPlaceholder.ts#L15

And I wonder if it gets the correct value back. Any debugging I can put on?

**Comment by mburumaxwell** [comment]
You can find out if the correct values are being passed to the container by looking at early logs in the task execution. Usually this is just before the docker image is pulled. If you want more debugging in the pipeline, you can enable it across the pipeline as per [docs](https://learn.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops).

From the look of things, I suspect the failures is because the variable `azureDevOpsAccessToken` is a template variable and not a pipeline variable. IIRC, template variables are only used when the pipeline is being created (compile time) and each task is assigned values as though they were declared inline. During execution those variables are not accessible. Replacement of variables in the registries section of your pipeline is done at runtime not compile time which means you cannot use a template variable.

If you are using the same value for tokens irrespective of the repository then you can use pipeline/stage/job variables instead of template ones. You would not need to change your configuration file. However, the pipeline template:

```yml
parameters:
  - name: repositories
    type: object
    default: []

steps:
- ${{ each repo in parameters.repositories }}:
  - task: dependabot@1
    displayName: ${{ repo }}
    inputs:
      azureDevOpsAccessToken: $(azureDevOpsAccessToken) 
      targetRepositoryName: ${{ repo }}
      gitHubAccessToken: $(githubAccessToken)
```

Your pipeline:

```yml
trigger: none # Disable CI trigger

schedules:
  - cron: "0 2 * * *" # daily at 2am UTC
    always: true # run even when there are no code changes
    branches:
      include:
        - master
    batch: true
    displayName: Daily

pool:
  vmImage: "ubuntu-latest"

variables:
- group: dependabot

steps:
- template: dependabot.yml
  parameters:
    repositories:
    - contoso-jobs
    - contuse-backend
```

If you are using different tokens to access the registries for each repo, you need multiple pipeline/stage/job variables to match each configuration.

Configuration 1:
```yml
version: 2
registries:
  nuget-azure-devops:
    type: "nuget-feed"
    url: "https://pkgs.dev.azure.com/contoso/_packaging/contoso1/nuget/v3/index.json"
    password: "PAT:${{AzureDevOpsAccessTokenJobs}}"
updates:
  - package-ecosystem: "nuget"
    directory: "/src"
```
Configuration 2:
```yml
version: 2
registries:
  nuget-azure-devops:
    type: "nuget-feed"
    url: "https://pkgs.dev.azure.com/contoso/_packaging/contoso2/nuget/v3/index.json"
    password: "PAT:${{AzureDevOpsAccessTokenBackend}}"
updates:
  - package-ecosystem: "nuget"
    directory: "/src"
```

Your pipeline and template remain as above but you should now declare `AzureDevOpsAccessTokenJobs` and `AzureDevOpsAccessTokenBackend` variables.

Note that the replacement works for the registries section of your configuration file. Other inputs such as `azureDevOpsAccessToken` and `gitHubAccessToken` can still be supplied using pipeline templates.

I would recommend that before you do many things at once:
1. Try a simple pipeline without templates and just for one repository to ensure the variable replacement works.
2. Change the pipeline to work for two repositories still without a template.
3. Since it works for two, look at the common things to allow you make a pipeline template.

This way you can tell if the issue is token replacement or the particular use of pipeline templates.
Hope this helps.

**Comment by reggieWX** [comment]
I have the same problem.
I'm using PAT to access the registry

This is the error I'm getting
`
"{\"$id\":\"1\",\"innerException\":null,\"message\":\"TF400813: The user 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.\",\"typeName\":\"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException,
`


My `azure-pipeline-dependabot.yml`

```
# Dependabot for Azure Devops
# https://marketplace.visualstudio.com/items?itemName=tingle-software.dependabot

schedules:
- cron: '0 0 * * *' # Every day at midnight
  always: true # run even when there are no code changes
  branches:
   include:
   - master
  batch: true
  displayName: Daily at midnight - Check for dependency updates

pool:
  vmImage: 'ubuntu-latest' # requires macos or ubuntu (windows is not supported)

steps:
- task: dependabot@1
  displayName: 'Check deps update'
  inputs:
    azureDevOpsAccessToken: '$(System.AccessToken)'
    extraEnvironmentVariables: EXCON_DEBUG=1
```


and `dependabot.yml`

```
version: 2
updates:
- package-ecosystem: "nuget" # See documentation for possible values
  directory: "/" # Location of package manifests
  schedule:
    interval: "daily"
registries:
  platform-engineering:
    type: nuget-feed
    url: https://pkgs.dev.azure.com/myrepo/_packaging/XXX.Engineering/nuget/v3/index.json
    token: $(personalAccessToken)
  trader:
    type: nuget-feed
    url: https://pkgs.dev.azure.com/myrepo/_packaging/Website/nuget/v3/index.json
    token: $(personalAccessToken)
```

**Comment by mburumaxwell** [comment]
@reggieWX The replacement format in the registries node is `${{...}}` and not `$(...)` 
Try change your configuration like this:
```diff
-    token: $(personalAccessToken)
+    token: ${{personalAccessToken}}
```

**Comment by reggieWX** [comment]
> @reggieWX The replacement format in the registries node is `${{...}}` and not `$(...)` Try change your configuration like this:
> 
> ```diff
> -    token: $(personalAccessToken)
> +    token: ${{personalAccessToken}}
> ```


Thanks for the response @mburumaxwell but that did not work as well. I even hardcoded the PAT in the `token` just to try it out but no luck.

Not sure if this information helps.


```
:host          => "pkgs.dev.azure.com"
  :local_address => "172.17.0.2"
  :local_port    => 45782
  :path          => "/xxx/_packaging/xxx.zzz/nuget/v3/index.json"
  :port          => 443
  :reason_phrase => "Unauthorized"
  :remote_ip     => "13.107.42.20"
  :status        => 401
  :status_line   => "HTTP/1.1 401 Unauthorized\r\n"
/home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-nuget-0.215.0/lib/dependabot/nuget/update_checker/repository_finder.rb:117:in `check_repo_response': The following source could not be reached as it requires authentication (and any provided details were invalid or lacked the required permissions): https://pkgs.dev.azure.com/xxx/_packaging/xxx.zzz/nuget/v3/index.json (Dependabot::PrivateSourceAuthenticationFailure)
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-nuget-0.215.0/lib/dependabot/nuget/update_checker/repository_finder.rb:45:in `build_url_for_details'
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-nuget-0.215.0/lib/dependabot/nuget/update_checker/repository_finder.rb:39:in `block in find_dependency_urls'
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-nuget-0.215.0/lib/dependabot/nuget/update_checker/repository_finder.rb:32:in `each'
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-nuget-0.215.0/lib/dependabot/nuget/update_checker/repository_finder.rb:32:in `flat_map'
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-nuget-0.215.0/lib/dependabot/nuget/update_checker/repository_finder.rb:32:in `find_dependency_urls'
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-nuget-0.215.0/lib/dependabot/nuget/update_checker/repository_finder.rb:23:in `dependency_urls'
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-nuget-0.215.0/lib/dependabot/nuget/update_checker/version_finder.rb:297:in `dependency_urls'
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-nuget-0.215.0/lib/dependabot/nuget/update_checker/version_finder.rb:192:in `v3_nuget_listings'
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-nuget-0.215.0/lib/dependabot/nuget/update_checker/version_finder.rb:105:in `available_v3_versions'
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-nuget-0.215.0/lib/dependabot/nuget/update_checker/version_finder.rb:57:in `versions'
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-nuget-0.215.0/lib/dependabot/nuget/update_checker/version_finder.rb:34:in `latest_version_details'
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-nuget-0.215.0/lib/dependabot/nuget/update_checker.rb:87:in `latest_version_details'
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-nuget-0.215.0/lib/dependabot/nuget/update_checker.rb:15:in `latest_version'
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.215.0/lib/dependabot/update_checkers/base.rb:234:in `numeric_version_up_to_date?'
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.215.0/lib/dependabot/update_checkers/base.rb:192:in `version_up_to_date?'
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.215.0/lib/dependabot/update_checkers/base.rb:33:in `up_to_date?'
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-nuget-0.215.0/lib/dependabot/nuget/update_checker.rb:55:in `up_to_date?'
	from ./update-script.rb:539:in `block in <main>'
	from ./update-script.rb:503:in `each'
	from ./update-script.rb:503:in `<main>'
##[error]The process '/usr/bin/docker' failed with exit code 1

```

**Comment by mburumaxwell** [comment]
Where is the `personalAccessToken` variable defined?

**Comment by Rutix** [comment]
@reggieWX you should prefix the token with a ":". This is needs to be send as Basic Auth and not bearer.

**Comment by mburumaxwell** [comment]
@Rutix that's for the correction.

@reggieWX the change should be 

```diff
-    token: $(personalAccessToken)
+    token: ':${{personalAccessToken}}'
```

The variable `personalAccessToken` should be a variable in the pipeline, stage or job. For security reasons this should be the a variable declared in the pipeline UI and instead of the definition.

Finally, check if the token is replaced in the environment variables passed to the docker container. Specifically the `DEPENDABOT_EXTRA_CREDENTIALS` variable.

**Comment by reggieWX** [comment]
Sorry for the confusion @mburumaxwell `personalAccessToken` is the same as `patForDependabot` due to testing I had to revoke it since I hardcoded in previous attempt. I'm not at work now. I will try again tomorrow and keep you all posted. Thanks

**Comment by mburumaxwell** [comment]
Azure DevOps is [currently having issues in my region](https://status.dev.azure.com) so it has taken quite some time to create a repro for you but Seems I finally have it:
Repository: https://dev.azure.com/tingle/dependabot/_git/repro-481
Pipeline run: https://dev.azure.com/tingle/dependabot/_build/results?buildId=54885&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=1f93c1a3-255b-505a-53c9-c382114aabf5
If you check the execution of the docker at the start of the task, you will noticed the token replaced (although redacted).

Hope this guides you @reggieWX and @jakubtrebacz-dev on how to setup the token replacement in the configuration file.

**Comment by mburumaxwell** [comment]
A more complete pipeline run example: https://dev.azure.com/tingle/dependabot/_build/results?buildId=54889&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=1f93c1a3-255b-505a-53c9-c382114aabf5

PAT has already been revoked.

**Comment by Rutix** [comment]
@mburumaxwell thanks for the reproduction! We also had problems with the issues of Azure so haven't been able to try it yet but I will soon and compare to the repo :).

**Comment by Rutix** [comment]
@mburumaxwell I started rebuilding it based on your repo and that seems to work. I am going to continue analyzing what I did wrong with my own implementation because that might help others and I am super curious about it :) since i have spend so many hours on this already. When I have found where it breaks I will report back.

**Comment by mburumaxwell** [comment]
@Rutix that is good to hear. Maybe [diffchecker](https://www.diffchecker.com/) will help finding the difference?

**Comment by Rutix** [comment]
@mburumaxwell I finally found out why it was not working for me and it's super silly and something I overlooked big time.

The error was in the config of the repository. I posted it earlier but I will post it again:

```YAML
version: 2
registries:
  nuget-azure-devops:
    type: "nuget-feed"
    url: "https://pkgs.dev.azure.com/redacted/_packaging/redacted/nuget/v3/index.json"
    password: "PAT:${{azureDevOpsAccessToken}}"
updates:
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "daily"
    milestone: 48085
```

The working one is:

```
version: 2
registries:
  nuget-azure-devops:
    type: "nuget-feed"
    url: "https://pkgs.dev.azure.com/redacted/_packaging/redacted/nuget/v3/index.json"
    token: "PAT:${{azureDevOpsAccessToken}}"
updates:
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "daily"
    milestone: 48085
```

As you can see in the registry i should have use the keyword `token` instead of `password` :(. I copied the base of the config from the official docs of dependabot but didn't notice there are multiple options there (`password`, `key`, `token`). I guess when it's password it will BASE64 encode stuff so it's messing up the token.

**Comment by mburumaxwell** [comment]
Thanks @Rutix for getting back.

@jakubtrebacz-dev and @reggieWX have you managed to solve yours?

**Comment by reggieWX** [comment]
Hey @mburumaxwell  @Rutix I got it working after this
https://github.com/tinglesoftware/dependabot-azure-devops/issues/481#issuecomment-1403190097

Thanks for the help! :)

**Comment by jakubtrebacz-dev** [comment]
Hi guys, 
Sorry for late reply, a lot of other work came up.
I have just tested this and it works perfectly fine on my end. I also thought I'd share my setup with anyone that wants a nice a clean setup for this.

Azure DevOps YAML Pipelines:
Pipeline name must follow this pattern: `Dependabot - name.of.your.repo`

It's easy to setup, you create a template for pipeline and populate your repos with configs.
Then just manage them form devops pipeline page via the name of your repo, and a one variables that you setup in the UI.
- Dependabot.GitHubAccessToken (just a github access token so that you can pull the docker image from github public repo without problems. Best to put it in a variable group and add to the pipeline definition below)

```yaml
trigger: none # Disable CI trigger
schedules:     # Use weekly schedule instead
  - cron: '0 7 * * 1' # on Mondays at 7am UTC
    always: true # run even when there are no code changes
    branches:
      include:
        - 'main'
    batch: true
    displayName: 'on Mondays'

variables:
  - name: Repository
    value: ${{ replace(variables['Build.DefinitionName'],'Dependabot - ', '') }}

stages:
  - stage: CheckDependencies
    displayName: 'Check Dependencies'
    jobs:
      - job: Dependabot
        displayName: 'Dependabot'
        pool:
          # Only works with MacOS and Linux
          vmImage: 'ubuntu-latest' 
        steps:
          # This step authenticates your agent user/context to use this repo/REST API
          - checkout: git://your_project_name/${{ variables.Repository }}

          # Creates $(VSS_NUGET_ACCESSTOKEN) for Private feeds
          - task: NuGetAuthenticate@1
            displayName: 'NuGet Private Feed Authentication'

          - task: dependabot@1
            displayName: 'Run Dependabot'
            inputs:
              setAutoComplete: true
              mergeStrategy: '1'
              gitHubAccessToken: '$(Dependabot.GitHubAccessToken)'
              azureDevOpsAccessToken: '$(System.AccessToken)'
              targetRepositoryName: '${{ variables.Repository }}'
```

And the `/.github/dependabot.yml`
- it doesn't need the schedule block in here.
```yaml
version: 2
updates:
- package-ecosystem: "nuget" # See documentation for possible values
  directory: "/" # Location of package manifests
  milestone: 6809 # work item identifier 
  open-pull-requests-limit: 1
  reviewers:
  - "email@example.com"
registries:
  private-nuget:
    type: nuget-feed
    url: https://pkgs.dev.azure.com/your_org/your_project/_packaging/feed_name/nuget/v3/index.json
    token: '${{VSS_NUGET_ACCESSTOKEN}}'
