### ISSUE TITLE
Passing work item into dependabot.yml config

### ISSUE THREAD

**Issue by dhavv** [tinglesoftware/dependabot-azure-devops#485]
Hi, I wanted to pass in `workItemID` azure pipelines variable to the milestone params in `.github/dependabot.yml` but it doesn't seem to work, any help?

```
pool:
  vmImage: ubuntu-latest

variables:
  workItemID: '123456'

steps:
- task: dependabot@1
  displayName: Dependabot
  inputs:
    useConfigFile: true
    abandonUnwantedPullRequests: false
    dockerImageRepository: 'tingle/dependabot-azure-devops'
```

Here is the `.github/dependabot.yml` file:

```
version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    milestone: ${{workItemID}}
```

I also tried `$(workItemID)` but doesn't seem to work as well
I couldn't find how to do it. Thank you in advance

**Comment by mburumaxwell** [comment]
The work item identifier is passed in the milestone option of each update the configuration file. Unfortunately, the value must be fixed and cannot be replaced in the pipeline.

```

version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    milestone: 1201 # must be fixed;
```

**Comment by Qluxzz** [comment]
This can be done by supplying the work item id as an environment variable to the docker container like this:

```yaml
- task: dependabot@1
  displayName: 'Run Dependabot'
  inputs:
    extraEnvironmentVariables: DEPENDABOT_MILESTONE=$(workItemId)
```

Here's an abbreviated example of a pipeline which creates a work item and then uses that for all created pull requests for that pipeline run.
```yml
jobs:
  - job: 'Dependabot'
    pool:
      # requires macos or ubuntu (windows is not supported)
      vmImage: 'ubuntu-latest'

    steps:
      - task: CreateWorkItem@1
        displayName: 'Create Issue for Dependabot'
        inputs:
          workItemType: 'Issue'
          title: 'Update Dependencies'
          createOutputs: true
          outputVariables: workItemId=ID

      - task: dependabot@1
        displayName: 'Run Dependabot'
        inputs:
          extraEnvironmentVariables: DEPENDABOT_MILESTONE=$(workItemId)
```
