### ISSUE TITLE
pacakge-lock.json file not updated

### ISSUE THREAD

**Issue by AndrewCraswell** [tinglesoftware/dependabot-azure-devops#512]
I've just integrated this extension into our Azure DevOps repository and yaml pipeline, and things seemed to be working. However, I noticed that each PR that was opened was only updating the `package.json` file, but not syncing the change with the `package-lockfile.json`. I already have dependabot integrated with several of my Github repos and this has worked out of the box, so I'm not sure what I've done wrong.

Here is my configuration file and pipeline template:

`.github/dependabot.yaml`
``` yaml
version: 2
registries:
  upstreams:
    type: npm-registry
    url: <redacted>
    token: PAT:${{AZURE_DEVOPS_PAT}}
updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - upstreams
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    milestone: 163501
    versioning-strategy: increase
```

`azure-pipelines.dependabot.yaml`
```yaml
schedules:
  - cron: "0 8 * * *"
    displayName: Daily Midnight (PST) Dependabot Run
    branches:
      include: [master]
    always: true

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
  - task: dependabot@1
    displayName: "Run Dependabot"
    inputs:
      packageManager: "npm"
    env:
      AZURE_DEVOPS_PAT: $(AZURE_DEVOPS_PAT)
```

**Comment by mburumaxwell** [comment]
@AndrewCraswell Should that be `package-lock.json` and not `package-lockfile.json`? Also, do you have a public repro for this?

**Comment by mburumaxwell** [comment]
@jussibility could you offer a public repro in AzDO?
We only need `package.json`, `package-lock.json`, `dependabot.yml`, and `azure-pipelines.yml` files.

**Comment by jussibility** [comment]
@mburumaxwell I created a public project for this but it seems I cannot run pipelines then. I've filled in the Azure DevOps Parallelism Request, but I do not know when and how they will respond to this.

**Comment by mburumaxwell** [comment]
The actual run of the pipeline is not as important. The repository containing the files is what is needed. I will clone and reproduce it from my end.

**Comment by jussibility** [comment]
https://dev.azure.com/jussibility/jussibility/_git/dependabot-test

**Comment by jussibility** [comment]
@mburumaxwell have you tried reproducing it?

**Comment by mburumaxwell** [comment]
@AndrewCraswell @jussibility does this work without setting  `open-pull-requests-limit: 0`?

**Comment by mburumaxwell** [comment]
According to my repro, the `package-lock.json` file would be updated.

https://dev.azure.com/tingle/dependabot/_build/results?buildId=57483&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=1f93c1a3-255b-505a-53c9-c382114aabf5

The PR is created without issues (`open-pull-requests-limit` is not set_
<img width="939" alt="Screenshot 2023-04-08 at 1 26 54 PM" src="https://user-images.githubusercontent.com/1645026/230716356-4c81dd24-6429-4617-9224-ee1669aceb80.png">

When running this for security only updates (`open-pull-requests-limit: 0`) there is no PR created because there is no vulnerability detected.

It could be there was an issue in the upstream that as fixed. Maybe you can try using the `dockerImageTag: latest` input in the extension?

**Comment by mburumaxwell** [comment]
@AndrewCraswell @jussibility is this resolved?
Will close soon.

**Comment by hendrickson-tyler** [comment]
@mburumaxwell Sorry to bump this closed issue, but I'm seeing this as well. I too am specifying `open-pull-requests-limit: 0` in `dependabot.yml` as our team is only concerned with vulnerabilities at the moment. Like the others, I only see Dependabot checking the dependencies in `package.json`.

When I run `npm audit` locally, I see one vulnerability for a transitive dependency and `npm audit fix` updates the `package-lock.json`. Based on the logs in the pipeline, it seems that it sees that the lockfile is there, but Dependabot doesn't check for this vulnerability at all:

![image](https://github.com/tinglesoftware/dependabot-azure-devops/assets/6372535/49ecb615-93ef-4f22-92e1-45fa316ab0f2)

For reference, here's my Dependabot config:
```yml
version: 2
updates:

  # Front-end dependencies.
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'env/dev'
    open-pull-requests-limit: 0 # Only opens PRs for vulnerabilities.

    # NOTE: The schedule here is overridden by the schedule in dependabot-pipeline.yml. Dependabot still requires
    # a schedule to be specified here, but it does nothing.
    schedule:
      interval: 'daily'
```
Is there a configuration option I might have missed? Happy to provide any other info that would be useful.
