### ISSUE TITLE
Terraform Modules In Azure DevOps

### ISSUE THREAD

**Issue by psyvision** [tinglesoftware/dependabot-azure-devops#520]
We have been trying to get this extension working with private Terraform modules hosted in Azure DevOps git and having problems accessing the module repository.

We are running using the `:latest` docker image tag.  We used to have the problem with `.git` being appended to repository URLs but that is now resolved.

We have two repositories both hosted under `{org}`:
- Project
- Infrastructure

We have tried both a `git` and a `terraform-registry` registry type as I'm not exactly sure which it would be, this is not a Terraform registry server, but both get the same error.

.github/dependabot.yml:
```yaml
version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/deploy/infrastructure"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    registries:
      - git-infra
      #- terra-infra

registries:
  git-infra:
    type: git
    url: https://dev.azure.com
    username: x-access-token
    password: PAT:${{AZDO_PAT}}

  terra-infra:
    type: terraform-registry
    url: https://dev.azure.com/{org}/Infrastructure/_git/Infrastructure
    token: PAT:${{AZDO_PAT}}
```

We include the repository as a source in our pipeline such that the access token gets permission to access the index.  Note this works for our other pipelines that use Terraform `plan`/`apply`:

pipeline.yml:
```yml
trigger: none

resources:
  repositories:
    - repository: infrastructure
      type: git
      name: Infrastructure/Infrastructure

stages:
  - stage: Dependabot
    displayName: Dependabot Stage
    condition: always()
    jobs:
      - job: Dependabot
        displayName: Dependabot
        condition: succeededOrFailed()
        continueOnError: true
        pool:
          name: "Azure Pipelines"
          vmImage: "ubuntu-latest"

        steps:
          - task: dependabot@1
            displayName: Dependabot
            inputs:
              useConfigFile: true
              openPullRequestsLimit: 10
            env:
              AZDO_PAT: $(System.AccessToken)
```

The output log from the run is:

```
/usr/bin/docker run --rm -i -e DEPENDABOT_PACKAGE_MANAGER=terraform -e DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=10 -e DEPENDABOT_DIRECTORY=/deploy/infrastructure -e DEPENDABOT_EXTRA_CREDENTIALS=[{"type":"git","url":"[https://dev.azure.com/{org}/Infrastructure/_git/Infrastructure","registry":null,"username":"x-access-token","password":"PAT:***"},{"type":"terraform_registry","url":"https://dev.azure.com/{org}/Infrastructure/_git/Infrastructure","registry":null,"token":"PAT:***"}](https://dev.azure.com/{org}/Infrastructure/_git/Infrastructure%22,%22registry%22:null,%22username%22:%22x-access-token%22,%22password%22:%22PAT:***%22%7D,%7B%22type%22:%22terraform_registry%22,%22url%22:%22https://dev.azure.com/{org}/Infrastructure/_git/Infrastructure%22,%22registry%22:null,%22token%22:%22PAT:***%22%7D)] -e DEPENDABOT_FAIL_ON_EXCEPTION=true -e AZURE_ORGANIZATION={org} -e AZURE_PROJECT=Project -e AZURE_REPOSITORY=Project -e AZURE_ACCESS_TOKEN=*** -e AZURE_MERGE_STRATEGY=squash tingle/dependabot-azure-devops:latest
....
<snip>
....
fatal: not a git repository: /home/dependabot/dependabot-core/../.git/modules/dependabot-core
fatal: not a git repository: /home/dependabot/dependabot-core/../.git/modules/dependabot-core
Using '[https://dev.azure.com:443/'](https://dev.azure.com/') as API endpoint
Working in {org}/Project/_git/Project, 'default' branch under '/deploy/infrastructure' directory
Looking for configuration file in the repository ...
🌍 --> GET https://dev.azure.com/{org}/Project/_apis/git/repositories/Project
🌍 <-- 200 https://dev.azure.com/{org}/Project/_apis/git/repositories/Project
🌍 --> GET https://dev.azure.com/{org}/Project/_apis/git/repositories/Project/stats/branches?name=master
🌍 <-- 200 https://dev.azure.com/{org}/Project/_apis/git/repositories/Project/stats/branches?name=master
🌍 --> GET https://dev.azure.com/{org}/Project/_apis/git/repositories/Project/items?path=.github/dependabot.yml&versionDescriptor.versionType=commit&versionDescriptor.version=708242262ce1a066d1749ccddef235b8759d3c97
🌍 <-- 200 https://dev.azure.com/{org}/Project/_apis/git/repositories/Project/items?path=.github/dependabot.yml&versionDescriptor.versionType=commit&versionDescriptor.version=708242262ce1a066d1749ccddef235b8759d3c97
Using configuration file at '/.github/dependabot.yml' 😎
Cloning repository into /home/dependabot/dependabot-updater/tmp/{org}/Project/_git/Project
Found 9 dependency file(s) at commit 708242262ce1a066d1749ccddef235b8759d3c97
 - /deploy/infrastructure/webapp.tf
 - /deploy/infrastructure/db.tf
 - /deploy/infrastructure/variables.tf
 - /deploy/infrastructure/locals.tf
 - /deploy/infrastructure/main.tf
 - /deploy/infrastructure/backend.tf
 - /deploy/infrastructure/outputs.tf
 - /deploy/infrastructure/versions.tf
 - /deploy/infrastructure/.terraform.lock.hcl
Parsing dependencies information
Found 5 dependencies
 - db::azure::{org}/Infrastructure/_git/Infrastructure ()
 - db_server::azure::{org}/Infrastructure/_git/Infrastructure ()
 - hashicorp/azurerm (3.14.0)
 - keyvault::azure::{org}/Infrastructure/_git/Infrastructure ()
 - web_app::azure::{org}/Infrastructure/_git/Infrastructure ()
🌍 --> GET https://dev.azure.com/{org}/_apis/connectionData
🌍 <-- 200 https://dev.azure.com/{org}/_apis/connectionData
🌍 --> GET https://dev.azure.com/{org}/Project/_apis/git/repositories/Project
🌍 <-- 200 https://dev.azure.com/{org}/Project/_apis/git/repositories/Project
🌍 --> GET https://dev.azure.com/{org}/Project/_apis/git/repositories/Project/pullrequests?api-version=6.0&searchCriteria.status=active&searchCriteria.creatorId=93a56af8-3932-4083-b5cb-b70b50108830&searchCriteria.targetRefName=refs/heads/master
🌍 <-- 200 https://dev.azure.com/{org}/Project/_apis/git/repositories/Project/pullrequests?api-version=6.0&searchCriteria.status=active&searchCriteria.creatorId=93a56af8-3932-4083-b5cb-b70b50108830&searchCriteria.targetRefName=refs/heads/master
Checking if db::azure::{org}/Infrastructure/_git/Infrastructure  needs updating
🌍 --> GET https://dev.azure.com/{org}/Infrastructure/_git/Infrastructure/info/refs?service=git-upload-pack
🌍 <-- 404 https://dev.azure.com/{org}/Infrastructure/_git/Infrastructure/info/refs?service=git-upload-pack
/home/dependabot/dependabot-core/common/lib/dependabot/git_metadata_fetcher.rb:78:in `fetch_upload_pack_for': The following git URLs could not be retrieved: https://{org}@dev.azure.com/{org}/Infrastructure/_git/Infrastructure (Dependabot::GitDependenciesNotReachable)
	from /home/dependabot/dependabot-core/common/lib/dependabot/git_metadata_fetcher.rb:17:in `upload_pack'
	from /home/dependabot/dependabot-core/common/lib/dependabot/git_metadata_fetcher.rb:51:in `head_commit_for_ref'
	from /home/dependabot/dependabot-core/common/lib/dependabot/git_commit_checker.rb:99:in `head_commit_for_local_branch'
	from /home/dependabot/dependabot-core/common/lib/dependabot/git_commit_checker.rb:92:in `head_commit_for_current_branch'
	from /home/dependabot/dependabot-core/terraform/lib/dependabot/terraform/update_checker.rb:118:in `latest_version_for_git_dependency'
	from /home/dependabot/dependabot-core/terraform/lib/dependabot/terraform/update_checker.rb:17:in `latest_version'
	from /home/dependabot/dependabot-core/terraform/lib/dependabot/terraform/update_checker.rb:37:in `updated_requirements'
	from /home/dependabot/dependabot-core/common/lib/dependabot/update_checkers/base.rb:292:in `changed_requirements'
	from /home/dependabot/dependabot-core/common/lib/dependabot/update_checkers/base.rb:278:in `requirements_up_to_date?'
	from /home/dependabot/dependabot-core/common/lib/dependabot/update_checkers/base.rb:35:in `up_to_date?'
	from bin/update-script.rb:570:in `block in <main>'
	from bin/update-script.rb:533:in `each'
	from bin/update-script.rb:533:in `<main>'
##[error]The process '/usr/bin/docker' failed with exit code 1
Finishing: Dependabot
```

Any ideas on the 404?  It to me suggests an authentication issue but I'm not quite sure where the problem lies
