### ISSUE TITLE
Variable replacement inconsistent within `dependabot.yml` config file

### ISSUE THREAD

**Issue by rgrace-puck** [tinglesoftware/dependabot-azure-devops#552]
`dependabot.yml` file:
```yml
version: 2
registries:
  my-registry:
    type: 'nuget-feed'
    url: 'https://pkgs.dev.azure.com/my_org/my_project/_packaging/my_feed/nuget/v3/index.json'
    token: 'PAT:${{ nugetAccessToken }}'

updates:
  - package-ecosystem: 'nuget'
    directory: '${{ packageManifestDirectory }}'
    schedule: 
      interval: 'weekly'
```

In the above file, `${{ nugetAccessToken }}` is replaced correctly with the value, but `${{ packageManifestDirectory }}` is not.
This behavior doesn't seem correct as just a few lines above, variable replacement works fine.
