### ISSUE TITLE
Allow to pass in the .npmrc file for npm authentication

### ISSUE THREAD

**Issue by ryanbowden** [tinglesoftware/dependabot-azure-devops#567]
I have created an pipline where we do the task that create the npmrc for all the feeds we have in our org. 

```
- task: npmAuthenticate@0
  displayName: 'npm authenticate'
  inputs:
    workingFile: '.npmrc'`
```

The issue is because the dependabot being run else where does not pick up the auth we have created. Can we get a way to pass through the values in this file so dependabot can use this without having to create new PAT tokens which may expire / if someone leaves the company break the pipelines.  

With nuget you can do this by this:

```
steps:
#Generates VSS_NUGET_ACCESSTOKEN variable
- task: NuGetAuthenticate@1
  displayName: 'Nuget Authentication'

- task: dependabot@1
  displayName: 'Run Dependabot'
  inputs:
    packageManager: 'nuget'
    targetBranch: 'develop'
    versioningStrategy: 'auto'
    extraEnvironmentVariables: DEPENDABOT_EXTRA_CREDENTIALS=[{"type":"nuget_feed","token":"$(VSS_NUGET_ACCESSTOKEN)","url":"url goes here"}]
```

We want to do the same with our NPM feed really, without needing to create PAT as the agent already has the permissions to access it.

Full current script:
```
schedules:
  - cron: '0 2 * * *' # daily at 2am UTC
    always: true # run even when there are no code changes
    branches:
      include:
      - 'develop'
    batch: true

trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: ubuntu-latest

steps:
- task: npmAuthenticate@0
  displayName: 'npm authenticate'
  inputs:
    workingFile: '.npmrc'

- script: npm ci

- task: dependabot@1
  displayName: 'Run Dependabot'
  inputs:
    setAutoComplete: true
    abandonUnwantedPullRequests: true
    mergeStrategy: 'noFastForward'

```

the NPM CI is there to confirm it can get the packages with the auth above but then fails in dependabot  
```
/home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-f8c48ef2f569/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:313:in `check_npm_response': The following source could not be reached as it requires authentication (and any provided details were invalid or lacked the required permissions): pkgs.dev.azure.com/{companyorg}/_packaging/{feed}/npm/registry (Dependabot::PrivateSourceAuthenticationFailure)
```

**Comment by SchulteMarkus** [comment]
Have you tried the Dependabot support for (npm) registries? Solved the challenge in my case.
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#npm-registry

```
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.MY_GITHUB_PERSONAL_TOKEN}}
    replaces-base: true
```

**Comment by mburumaxwell** [comment]
@ryanbowden I believe the reason why PATs exist is to ensure that security-wise you are safer with expiry and scoping. No one encourages checking in a PAT into source control.

Passing in a `.npmrc` file would require changing the logic that [dependabot-core](https://github.com/dependabot/dependabot-core) uses to parse files. It is expected that the files required are in the repository file tree.

By the way, dependabot runs inside a docker container so it doesn't have access to credentials that you added to your current pipeline run. Even if you add `NpmAuthenticate@1` or `NuGetAuthenticate@1` tasks. The credentials have to be passed to the container.

The alternative I encourage the most in dealing with no one wanting to take up this work/responsibility in your workplace, is to create a dedicated account e.g. `dependabot@contoso.com` in Azure DevOps (it doesn't need a mailbox of any type). You would create the PAT here and every so often you would renew it. That way there will be no need to worry about employee attrition.

Another alternative, (the most popular one) is to use the pipeline's token and not an individual's token. Of course, you will have to give necessary permissions (can be tedious) and have PRs with names of entities that are not real people, but you would never need to renew a PAT. SO long as your organization is running, you are good to go.

**Comment by mburumaxwell** [comment]
Maybe the new support for managed identities and service principals will help in your scenario.
https://devblogs.microsoft.com/devops/introducing-service-principal-and-managed-identity-support-on-azure-devops/

**Comment by eli-gc** [comment]
I was able to connect to a private npm repository by using System.AccessToken as the token. I had to pass it through the task using env and setting that env variable to the token field in registries in .github/dependabot.yaml

**Comment by ryanbowden** [comment]
> I was able to connect to a private npm repository by using System.AccessToken as the token. I had to pass it through the task using env and setting that env variable to the token field in registries in .github/dependabot.yaml

@eli-gc are you able to give a quick safe to share example on how you managed this so I can try with that pipeline recently broke and not been able to fix it since. be good to have an example to help others.

**Comment by eli-gc** [comment]
@ryanbowden Sure, no problem. 
I'm not sure if it matters, but we use a service connection which is identified by the gitHubConnection field.

Task in pipeline yaml:
```
- task: dependabot@1
  inputs:
    useConfigFile: true
    setAutoComplete: true
    mergeStrategy: '1'
    gitHubConnection: 'arbitrary_github_connection'
  env:
    TOKEN: $(System.AccessToken)
   ```

.github/dependabot.yaml:
```
version: 2
registries:
   your-npm-registry-name:
      type: npm-registry
      url: https://your-registry-url
      token: ${{TOKEN}}
updates:
   - package-ecosystem: "npm"
     directory: "/"
     schedule:
        interval: "daily"
```
