### ISSUE TITLE
Dependabot fails when an update is found

### ISSUE THREAD

**Issue by jozephp** [tinglesoftware/dependabot-azure-devops#577]
Dependabot fails when an update is found for golang dependancy and silently proceeds to check the next dependency 

## dependabot.yml
```yaml
# Maintain dependencies for gomod everyday
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "*"
      - dependency-type: "all"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    open-pull-requests-limit: 10
    commit-message:
      prefix: "Dependabot:Gomod:"
```

## Output 
```
Using configuration file at '/.github/dependabot.yml' 😎
Cloning repository into /home/dependabot/dependabot-updater/tmp/repo_name/_git/******
Found 2 dependency file(s) at commit 76f2c7d1fbaac5b2c165f4a2bb960d9acf4fe11c
 - /go.mod
 - /go.sum
Parsing dependencies information
.
.
.
.

Checking if github.com/Azure/azure-sdk-for-go 67.3.0+incompatible needs updating
Requirements to unlock own
Requirements update strategy 
Error working on updates for github.com/Azure/azure-sdk-for-go 67.3.0+incompatible (continuing)
bin/update-script.rb:223:in `match?': target of repeat operator is not specified: /*/ (RegexpError)
	from bin/update-script.rb:223:in `block in allow_conditions_for'
	from bin/update-script.rb:223:in `each'
	from bin/update-script.rb:223:in `find'
	from bin/update-script.rb:223:in `allow_conditions_for'
	from bin/update-script.rb:601:in `block in <main>'
	from bin/update-script.rb:533:in `each'
	from bin/update-script.rb:533:in `<main>'
Checking if github.com/Azure/azure-sdk-for-go/sdk/azidentity 1.2.0 needs updating
No update needed for github.com/Azure/azure-sdk-for-go/sdk/azidentity 1.2.0

```
