### ISSUE TITLE
[Feature Request] Ability to have PRs created as drafts

### ISSUE THREAD

**Issue by 18swenskiq** [tinglesoftware/dependabot-azure-devops#583]
As far as I can tell, there is currently no way to have the PRs created as draft. From what I can tell this should be possible via the `create-pull-request` task that is being used inside of the dependabot task, however I don't see an option for it in any of the settings for this task.

**Comment by mburumaxwell** [comment]
@18swenskiq could you explain why you need this particular feature?

**Comment by 18swenskiq** [comment]
Currently, our system is built so that when a Pull Request is created to Master, it kicks off an automation run.

We are also currently running this once a week, and as you can imagine we don't need multiple automation runs automatically happening, especially when most are patch versions, and also considering we might not even get to it until later in the week when master is different anyway (and thus pushing into master would require a new automation run anyway).

Being able to create the PR as a draft gets around this by just not running any automation at all until we are ready

**Comment by mburumaxwell** [comment]
I believe I understand the scenario. To change creation of PRs you would need to update the upstream [around here](https://github.com/dependabot/dependabot-core/blob/d0bd472495eda2eabb71040a59dbbfeb4dfb4931/common/lib/dependabot/clients/azure.rb#L174-L193) and also make a case for it in the upstream repo.

What we have done on our end is to skip some steps and stages in the pipelines if we detect that they are updates from dependabot. That way, the running time is reduced by almost half. Below are some examples, I hope they help.

For example:
```yml
- task: DockerCompose@0
  displayName: 'Build docker images'
  # exclude PR branches for dependabot
  condition: |
    and
    (
      succeeded(),
      not(contains(variables['System.PullRequest.SourceBranch'], 'dependabot/'))
    )
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: '$(dockerRegistryEndpoint)'
    dockerComposeFile: '$(dockerComposeFile)'
    additionalDockerComposeFiles: '$(additionalDockerComposeFiles)'
    action: 'Build services'
```

On a stage:

```yml
- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: DeployPR
    displayName: Deploy PR for Review
    environment: 'MyEnv'
    pool:
      vmImage: 'ubuntu-latest'
    # only pr branches
    condition: |
      and
      (
        succeeded(),
        startsWith(variables['Build.SourceBranch'], 'refs/pull/'),
        not(contains(variables['System.PullRequest.SourceBranch'], 'dependabot/'))
      )
// add the other stage logic/steps
```
