### ISSUE TITLE
Cannot download the Dependabot-updater container image

### ISSUE THREAD

**Issue by HumanPrinter** [tinglesoftware/dependabot-azure-devops#637]
As of today, our Azure DevOps dependabot-pipelines fail, because the dependabot-updater container image cannot be found.

The pipeline YAML we use is very basic:
```
- task: dependabot@1
  inputs:
    azureDevOpsAccessToken: '$(PAT)'
    abandonUnwantedPullRequests: false
    setAutoComplete: true
  displayName: Run Dependabot
```

When executing the task, the task-code tries to download the image 'ghcr.io/tinglesoftware/dependabot-updater:0.17', but that tag no longer exists om the container registry. Looking at https://github.com/tinglesoftware/dependabot-azure-devops/pkgs/container/dependabot-updater only ci-* tags are available. We could fix this by hardcoding the image tag to latest, but I don't think that is how it is supposed to work.

I suspect the cleanup action that cleans the Github container registry is a bit overzealous.

We are running the latest available version (according to the Marketplace) of the Azure DevOps extension (0.17.1.489)
