### ISSUE TITLE
Shared nuget.config in the root directory and .csproj files in subdirectories

### ISSUE THREAD

**Issue by tnc1997** [tinglesoftware/dependabot-azure-devops#639]
Firstly I would like to thank you very much for your work on this extension. In [this](https://github.com/tinglesoftware/dependabot-azure-devops/issues/460#issuecomment-1384812040) comment you mention that a `nuget.config` file needs to exist in the same location as the `.csproj` file, in order to correctly use both private feeds and the default nuget.org feed. In solutions with multiple projects, one shared `nuget.config` file is often created in the root directory. Is this something that might be able to be supported by this extension, as it would alleviate duplicating the `nuget.config` file in each subdirectory?

```text
.
├── src/
│   ├── WebApp/
│   │   ├── Program.cs
│   │   └── WebApp.csproj
│   └── WebApi/
│       ├── Program.cs
│       └── WebApi.csproj
├── nuget.config
└── Solution.sln
```

```yaml
version: 2
registries:
  common:
    token: PAT:${{SYSTEM_ACCESSTOKEN}}
    type: nuget-feed
    url: https://pkgs.dev.azure.com/xyz/_packaging/common/nuget/v3/index.json
updates:
  - directory: /src/WebApp
    package-ecosystem: nuget
    schedule:
      interval: daily
  - directory: /src/WebApi
    package-ecosystem: nuget
    schedule:
      interval: daily
```

https://learn.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#config-file-locations-and-uses

> In a solution folder, settings apply to all projects in subfolders. Note that if a config file is placed in a project folder, it has no effect on that project. When restoring a project on the command line, the project's directory is treated as the solution directory, which can lead to differences in behaviour when restoring the project vs solution.

**Comment by mburumaxwell** [comment]
The nuget.config file should be at the root of the folder specified by the `directory` parameters.
To multiple projects in the folder structure you have, you would need to change your dependabot.yml file to:

```yaml
version: 2
registries:
  common:
    token: PAT:${{SYSTEM_ACCESSTOKEN}}
    type: nuget-feed
    url: https://pkgs.dev.azure.com/xyz/_packaging/common/nuget/v3/index.json
updates:
  - directory: /
    package-ecosystem: nuget
    schedule:
      interval: daily
```

Dependabot can read solution files to find actual project files so you do not need to specify each project folder separately in the dependabot.yml file.
If you need a different schedule/ignore for each, you will have to duplicate the nuget.config file with similar issues as you have read in the official nuget docs.
