### ISSUE TITLE
Pull request cannot be activated

### ISSUE THREAD

**Issue by zacqed** [tinglesoftware/dependabot-azure-devops#64]
`Error: Message TF401398: The pull request cannot be activated because the source and/or the target branch no longer exists, or the requested refs are not branches`

YAML:
```
steps:
- task: dependabot@1
  inputs:
    packageManager: "pip"
    openPullRequestsLimit: 1
    versioningStrategy: "auto"
    targetBranch: development
```

Detailed Logs:

```
Digest: sha256:64616d4509746920bc7be0348e44a10b0d9ea6e9b87668b91dace9e5e933d1d9
Status: Downloaded newer image for tingle/dependabot-azure-devops:0.2
Using 'dev.azure.com' as hostname
Fetching pip dependency files for organisation/Kep/_git/Kep
Targeting 'development' branch under '/' directory
Using 'auto' versioning strategy
Parsing dependencies information
Checking if flask-appbuilder 3.1.1 needs updating
Requirements to unlock own
Updating flask-appbuilder from 3.1.1 to 3.2.0
Submitting flask-appbuilder pull request for creation. Failed! PR already exists or an error has occurred.
Status: 400.
Message TF401398: The pull request cannot be activated because the source and/or the target branch no longer exists, or the requested refs are not branches
Limit of open pull requests (1) reached.
```

**Comment by mburumaxwell** [comment]
@zacqed what other things did you do?

**Comment by zacqed** [comment]
Here is what was done:
1. create a .azuredevops folder in the root of the directly
2. Included the dependabot.yml file 
3. Included DockerFile
4. Included update_script.rb file
5. Update the permission for the build service to be able to open PR / contribute
6. Ran this configuration in a azure pipeline with the extension installed.

The content of yml file is as follows:
```
trigger: none # Disable CI trigger

schedules:
- cron: "0 0 * * *" # daily at 2am UTC
  always: true # run even when there are no code changes
  branches:
    include:
      - development
  batch: true
  displayName: Daily

pool:
  vmImage: "ubuntu-latest" # requires macos or ubuntu (windows is not supported)

steps:
- task: dependabot@1
  inputs:
    packageManager: "pip"
    openPullRequestsLimit: 1
    versioningStrategy: "auto"
    targetBranch: "depend-new"
```
