### ISSUE TITLE
cant't get it to work with maven feed

### ISSUE THREAD

**Issue by davidkarlsen** [tinglesoftware/dependabot-azure-devops#647]
my pipeline:
```yaml
# This task reads the standard dependabot configuration found under .github/dependabot.yml
steps:
  - task: dependabot@1
    env:
      SYSTEM_ACCESSTOKEN: '$(System.AccessToken)'
    inputs:
      azureDevOpsAccessToken: '$(System.AccessToken)'
```

the `.github/dependabot.yml`:
```yaml
version: 2
registries:
  npp:
    type: maven-repository
    url: https://pkgs.dev.azure.com/myOrg/_packaging/MyFeed/maven/v1
    token: PAT:${{SYSTEM_ACCESSTOKEN}}
    replaces-base: true
updates:
  - package-ecosystem: "maven"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
```

pipeline passes as green, but with no PRs, and I see 401 in response to the feed requests.
I've seen various issues in the tracker, but not conclusive on how it should look. Maybe an example in the readme would be good?

**Comment by mburumaxwell** [comment]
Repro? Logs?

**Comment by mburumaxwell** [comment]
your pipeline:
```yaml
steps:
  - task: dependabot@1
```

Your `.github/dependabot.yml` file:
```yaml
version: 2
registries:
  npp:
    type: maven-repository
    url: https://pkgs.dev.azure.com/myOrg/_packaging/MyFeed/maven/v1
    username: myOrg
    password: ${{SYSTEM_ACCESSTOKEN}}
updates:
  - package-ecosystem: "maven"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
```

**Comment by davidkarlsen** [comment]
I got it working but I am away from work right now. Will get back with some details and close the issue.

**Comment by davidkarlsen** [comment]
My dependabot config:

```yaml 
version: 2
registries:
  npp:
    type: maven-repository
    url: https://pkgs.dev.azure.com/<<MYORG>>/_packaging/<<myfeed>>/maven/v1
    #token: PAT:${{System.AccessToken}} //did not work
    username: <<MYORG>>
    password: ${{SYSTEM_ACCESSTOKEN}}
    replaces-base: true
updates:
  - package-ecosystem: "maven"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
```

the pipeline:
```yaml
trigger: none # Disable CI trigger

schedules:
  - cron: '0 2 * * *' # daily at 2am UTC
    always: true # run even when there are no code changes
    branches:
      include:
        - main
    batch: true
    displayName: Dependabot

pool:
  vmImage: 'ubuntu-latest'

# This task reads the standard dependabot configuration found under .github/dependabot.yml
steps:
  - task: dependabot@1
```
