### ISSUE TITLE
API rate limit exceeded

### ISSUE THREAD

**Issue by zacqed** [tinglesoftware/dependabot-azure-devops#70]
The dependabot configuration has following:

```
- task: dependabot@1
  inputs:
    packageManager: "pip"
    openPullRequestsLimit: 10
    versioningStrategy: "auto"
    gitHubConnection: $(GITHUBVARIABLE)

```

and the githubvariable is defined in the pipeline

![image](https://user-images.githubusercontent.com/1675591/112433144-d7680b00-8d67-11eb-9f0a-aa4e55fc897d.png)

However while running the pipeline, we continue to receive this error. Is there a different way to set it?

`Submitting joblib pull request for creation. /vendor/ruby/2.6.0/gems/octokit-4.20.0/lib/octokit/response/raise_error.rb:14:in on_complete: GET https://api.github.com/repos/joblib/joblib/commits?sha=1.0.1: 403 - API rate limit exceeded for 52.156.121.197. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting (Octokit::TooManyRequests)
`
