### ISSUE TITLE
Dependency updates not respecting "ignore" section

### ISSUE THREAD

**Issue by rgrace-puck** [tinglesoftware/dependabot-azure-devops#740]
Hello,
I'm trying to ignore updates for a NuGet package ("Moq") in my dependabot.yml but it keeps creating pull requests anyway.

It looks like someone was having this issue recently (https://github.com/dependabot/dependabot-core/issues/7377) but it was filed under the official repository and no conclusion was reached.

I've tried the possible fixes mentioned in #582 (Removing BOM, removing comments, etc..) but nothing fixed it.

dependabot.yml:
```yml
version: 2
registries:
  my-feed:
    type: 'nuget-feed'
    url: 'https://pkgs.dev.azure.com/<ORG>/<PROJECT>/_packaging/<FEED>/nuget/v3/index.json'
    token: 'PAT:${{ nugetAccessToken }}'

updates:
  - package-ecosystem: 'nuget'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'Moq'
```
I've also tried all lowercase "moq" but to no avail. 

Logs from pipeline:
```
🌍 --> GET https://pkgs.dev.azure.com/ORG/c7256fd7-af73-4240-bada-9c3dafbc9559/_packaging/aaaa56ab-5e62-487b-a5aa-b67fee0f0912/nuget/v3/flat2/moq/index.json
🌍 <-- 200 https://pkgs.dev.azure.com/ORG/c7256fd7-af73-4240-bada-9c3dafbc9559/_packaging/aaaa56ab-5e62-487b-a5aa-b67fee0f0912/nuget/v3/flat2/moq/index.json
Requirements to unlock own
Requirements update strategy 
Updating Moq from 4.18.4 to 4.20.2
Submitting Moq pull request for creation.
🌍 --> GET https://dev.azure.com/ORG/PROJECT/_apis/git/repositories/REPO/commits
🌍 <-- 200 https://dev.azure.com/ORG/PROJECT/_apis/git/repositories/REPO/commits
🌍 --> GET https://pkgs.dev.azure.com/ORG/c7256fd7-af73-4240-bada-9c3dafbc9559/_packaging/aaaa56ab-5e62-487b-a5aa-b67fee0f0912/nuget/v3/flat2/moq/4.20.2/moq.nuspec
🌍 <-- 200 https://pkgs.dev.azure.com/ORG/c7256fd7-af73-4240-bada-9c3dafbc9559/_packaging/aaaa56ab-5e62-487b-a5aa-b67fee0f0912/nuget/v3/flat2/moq/4.20.2/moq.nuspec
🌍 --> GET https://github.com/moq/moq.git/info/refs?service=git-upload-pack
🌍 <-- 200 https://github.com/moq/moq.git/info/refs?service=git-upload-pack
🌍 --> GET https://github.com/moq/moq.git/info/refs?service=git-upload-pack
🌍 <-- 200 https://github.com/moq/moq.git/info/refs?service=git-upload-pack
🌍 --> GET https://dev.azure.com/ORG/PROJECT/_apis/git/repositories/REPO/refs?filter=heads/dependabot/nuget/Moq-4.20.2
🌍 <-- 200 https://dev.azure.com/ORG/PROJECT/_apis/git/repositories/REPO/refs?filter=heads/dependabot/nuget/Moq-4.20.2
🌍 --> POST https://dev.azure.com/ORG/PROJECT/_apis/git/repositories/REPO/pushes?api-version=5.0
🌍 <-- 201 https://dev.azure.com/ORG/PROJECT/_apis/git/repositories/REPO/pushes?api-version=5.0
🌍 --> GET https://dev.azure.com/ORG/PROJECT/_apis/git/repositories/REPO
🌍 <-- 200 https://dev.azure.com/ORG/PROJECT/_apis/git/repositories/REPO
🌍 --> POST https://dev.azure.com/ORG/PROJECT/_apis/git/repositories/REPO/pullrequests?api-version=5.0
🌍 <-- 201 https://dev.azure.com/ORG/PROJECT/_apis/git/repositories/REPO/pullrequests?api-version=5.0
Created pull request for Moq (#1292).
```
