### ISSUE TITLE
Wrong argument type nil (expected Regexp) (TypeError)

### ISSUE THREAD

**Issue by PaulMoney** [tinglesoftware/dependabot-azure-devops#769]
Hello,

I'm attempting to integrate Dependabot with Azure DevOps Pipelines, but I'm encountering the following error::

<img width="668" alt="image" src="https://github.com/tinglesoftware/dependabot-azure-devops/assets/65279837/ebba19ce-769b-4df9-b174-936eaa6da3f9">

Here is the command line that passes environment variables to the Docker container:

```
/usr/bin/docker run --rm -i -e DEPENDABOT_PACKAGE_MANAGER=npm -e DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=5 -e DEPENDABOT_DIRECTORY=/ -e DEPENDABOT_TARGET_BRANCH=dev -e DEPENDABOT_ALLOW_CONDITIONS=[{"dependency-type":"production"}] -e DEPENDABOT_FAIL_ON_EXCEPTION=true -e AZURE_ORGANIZATION=superhow -e AZURE_PROJECT=StreamPay -e AZURE_REPOSITORY=streampay-backend -e AZURE_ACCESS_TOKEN=*** -e AZURE_MERGE_STRATEGY=squash ghcr.io/tinglesoftware/dependabot-updater-npm:1.20
```

This is the content of my `dependabot.yml` file that is used by the pipeline task:

```
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "monday"
    allow:
      # Allow only production dependencies to update
      - dependency-type: production
    target-branch: "dev"
    open-pull-requests-limit: 5
```

I'd greatly appreciate any help in resolving this issue. Thank you in advance for your assistance!
