### ISSUE TITLE
Confusion around variables/inputs, pipeline.yml and dependabot.yml

### ISSUE THREAD

**Issue by ghs** [tinglesoftware/dependabot-azure-devops#810]
Hi,

Hopefully I am not the only one, but I find it pretty confusing when it comes to these 3 points from the title of this issue. At least for me, this comes from the lack of documentation or the documentation not being updated. Hope I am wrong, but will be happy for suggestions or even indications for the right implementation and/or direction.

First and perhaps most simple is related to .github/dependabot.yml
If any of these inputs (packageEcosystem, targetBranch, targetRepositoryName) are provided, I get the same message as in https://github.com/tinglesoftware/dependabot-azure-devops/issues/495, `##[error]Configuration file not found at possible locations: /.github/dependabot.yaml, /.github/dependabot.yml`. So having the following task results into an error:

```
- task: dependabot@1
     displayName: "Run Dependabot"
     inputs:
       packageEcosystem: "npm"
       targetBranch: "main"
       targetRepositoryName: "some-repository"
       openPullRequestsLimit: 1
       milestone: $(workItemId)
```
Removing them works fine, but results into another error: `##[error] The process '/usr/bin/docker' failed with exit code 1.`. This could be related to the fact that where my pipeline file is located, there is no package.json. The error really should indicate something.

Then comes the question about how then to run agains multiple repositories just like in https://github.com/tinglesoftware/dependabot-azure-devops/issues/328 when there is an error for missing .github/dependabot.yml file when using the previously mentioned inputs?
And because there is not a lot, sorry don't want to say at all, documentation about if when using anything from packageEcosystem, targetBranch, targetRepositoryName then an access token or more variables should be provided, like project id, who knows what more...

I understand that adding "a configuration file stored at .github/dependabot.yml or .github/dependabot.yaml conforming to the [official spec](https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates)." but it was confusing when the pipeline has its own schedule and the dependabot.yml file requires also a schedule because this property is required and if not provided most probably will result into another failure.

Also there are some variables which could be found in parseConfigFile.ts file but not reflected in any documentation, and this makes the whole setup really frustrating... :(

So, after all these complains :P I'd appreciate if someone could help :)

The current setup of mine is as follows:

repository-1
- src/
- package.json

repository-2
- src/
- requirements.txt

ops-repository
- .github/dependabot.yml
- dependabot/pipelines.yml

(only ops-repository has .github/dependabot.yml)

Where the pipelines.yml file contains:
```
schedules:
  - cron: "*/5 * * * *"
    displayName: "Dependabot"
    always: true
    branches:
      include:
        - main

trigger: none

stages:
  - stage: CheckDependencies
    displayName: "Check dependencies"
    jobs:
      - job: Dependabot
        displayName: "Run Dependabot"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: CreateWorkItem@2
           ...

          - task: dependabot@1
            displayName: "Run Dependabot npm"
            inputs:
              packageEcosystem: "npm"
              targetBranch: "main"
              targetRepositoryName: "repository-1"
              openPullRequestsLimit: 1
              milestone: $(workItemId)

          - task: dependabot@1
            displayName: "Run Dependabot pip"
            inputs:
              packageEcosystem: "pip"
              targetBranch: "main"
              targetRepositoryName: "repository-2"
              openPullRequestsLimit: 1
              milestone: $(workItemId)

```

and dependabot.yml:

```
version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    day: "thursday"
    time: "00:00"
    timezone: "UTC"
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    day: "thursday"
    time: "00:00"
    timezone: "UTC"
```

And the questions:
1. How to run this with targetBranch, packageEcosystem and targetRepositoryName without getting the "not found dependabot.yml" file? Is there a need for some additional variables like access token, project ID, etc? And if these are not needed, then how to define different repository within the dependabot.yml file is there is no such property https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file?
2. From https://github.com/tinglesoftware/dependabot-azure-devops/issues/485, does it means the milestone have to passed as `extraEnvironmentVariables` otherwise using simply `milestone` to the task will not work?
3. Where have to define things, pipeline or dependabot.yml? Is there a need to have N amount of tasks for each repo or one task which will then be handled by all specs from the dependabot.yml?
4. What would be the outcome if the pipeline schedule time is the same as dependabot.yml? What if the pipeline runs at midnight but until the dependabot.yml file is read and executed, is already few minutes later?

Big thanks!
