### ISSUE TITLE
[NuGet] [error]Registries: 'nuget-azure-devops,nuget-public' have not been referenced by any update

### ISSUE THREAD

**Issue by Rutix** [tinglesoftware/dependabot-azure-devops#823]
Since the 21th of September our scheduled pipeline which checks each night for updates started failing. We are lost to the cause of this failure. The only error we are getting is:

##[error]Registries: 'nuget-azure-devops,nuget-public' have not been referenced by any update

Our .github/dependabot.yml looks like this:

```yaml
version: 2
registries:
  nuget-azure-devops:
    type: 'nuget-feed'
    url: 'https://pkgs.dev.azure.com/{redacted}/_packaging/{redacted}/nuget/v3/index.json'
    token: ':${{azureDevOpsAccessToken}}'
  nuget-public:
    type: 'nuget-feed'
    url: 'https://api.nuget.org/v3/index.json'
updates:
  - package-ecosystem: 'nuget'
    directory: '/src'
    schedule:
      interval: 'daily'
    milestone: 48085
    ignore:
      - dependency-name: 'Microsoft.AspNetCore.*'
        update-types: ['version-update:semver-major']
      - dependency-name: 'Microsoft.VisualStudio.Web.CodeGeneration.Design'
        update-types: ['version-update:semver-major']
```

Do you have any pointers on what could be going wrong? Has there been a new update in recent days?
