### ISSUE TITLE
Referenced registries: '*' have not been configured in the root of dependabot.yml

### ISSUE THREAD

**Issue by robvangeloven** [tinglesoftware/dependabot-azure-devops#826]
**Describe the bug**
Specifying registries as "*" will give the error "Referenced registries: '*' have not been configured in the root of dependabot.yml"

This worked in version 1.20.0

Possibly caused by change #781

**To Reproduce**
Using this dependabot.yml as config:
```yml
version: 2

registries:
  private:
    type: 'nuget-feed'
    url: '<private https feed>'
  public:
    type: 'nuget-feed'
    url: 'https://api.nuget.org/v3/index.json'

updates:
  - package-ecosystem: 'nuget'
    directory: '/Source'
    registries: "*"
    schedule:
      interval: 'daily'
    # Open PR against branch develop
    target-branch: 'develop'
    milestone: 12345
```

**Expected behavior**
According to the docs this should be a valid config:  [https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#registries]()

**Extension (please complete the following information):**
 - Host: Azure DevOps
 - Version 1.21.0

**Server (please complete the following information):**
 - Region westeurope
 - Version 1.21.0
