### ISSUE TITLE
dependabot task fails with error: Tried to load unspecified class: Symbol (Psych::DisallowedClass)

### ISSUE THREAD

**Issue by kotareddyp** [tinglesoftware/dependabot-azure-devops#833]
Dependabot Azure Devops pipeline fails with error:
/home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/psych-5.1.0/lib/psych/class_loader.rb:99:in `find': Tried to load unspecified class: Symbol (Psych::DisallowedClass)

1. Create a dependabot.yml file in the .github folder at the root of the repository with contents

   ```yml
   version: 2
   registries:
     public:
       type: nuget-feed
       url: https://api.nuget.org/v3/index.json
   updates:
     - package-ecosystem: nuget
       directory: '/'
       registries:
         - public
       schedule:
         interval: weekly
       open-pull-requests-limit: 50
   ```
2. create a pipeline in Azure devops with this yml

   ```yml
   schedules:
     - cron: "0 20 * * FRI"
       displayName: 'Weekly Run'
       always: true
       branches:
         include:
           - 'master'

   trigger: none
   pool:
     vmImage: 'ubuntu-latest'
   stages:
     - stage: CheckDependencies
       displayName: 'Check Dependencies'
       jobs:
         - job: Dependabot
           displayName: 'Run Dependabot'
           pool:
             vmImage: 'ubuntu-latest'
           steps:
           - task: dependabot@1
             inputs:
               failOnException: false
               gitHubConnection: 'Github- HKelly'
   ```

**Expected behavior**
Pipeline should run successfully

**Screenshots**
![image](https://github.com/tinglesoftware/dependabot-azure-devops/assets/86082654/4a3c0422-d720-4308-8eff-a9b7aacdfcf9)

**Extension (please complete the following information):**
 - Host: Azure Devops
