### ISSUE TITLE
Add possibility to use branches when using targetRepositoryName

### ISSUE THREAD

**Issue by michvllni** [tinglesoftware/dependabot-azure-devops#835]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to pass a branch when using the extension for more than one repository.
Thus, the extension always searches for the dependabot.yml in the default branch.
This is especially useful for staged projects where the config might differ from branch to branch

**Describe the solution you'd like**
It would be great if it was possible to pass the targetbranch the same way as the targetRepositoryName like
```yml
  - task: dependabot@1
    inputs:
      targetRepositoryName: myrepository
      targetRepositoryBranchName: mybranch
```

**Describe alternatives you've considered**
The alternative I'm forced to use is that I move all configs to the default branches which is cumbersome
