### ISSUE TITLE
What am I missing? - "Security updates are enabled but a GitHub token is not supplied!"

### ISSUE THREAD

**Issue by piejanssens** [tinglesoftware/dependabot-azure-devops#839]
.github/dependabot.yml config:
```yaml
# Maintain dependencies for npm
# Basic set up for three package managers

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/app'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 0

  # Maintain dependencies for npm
  - package-ecosystem: 'npm'
    directory: '/backend'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 0

```

Pipeline config:
```yaml
trigger: none # Disable CI trigger

schedules:
  - cron: '0 2 * * *' # daily at 2am UTC
    always: true # run even when there are no code changes
    branches:
      include:
        - master
    batch: true
    displayName: Daily

pool:
  vmImage: 'ubuntu-latest' # requires macos or ubuntu (windows is not supported)

steps:
  - task: dependabot@1
    inputs:
      azureDevOpsAccessToken: '$(System.AccessToken)'
```

Pipeline output:
```
Digest: sha256:896faa243ee09ce13609bc9018eb08b5ccc8b8a3e5338bc49baee766f5ebef23
Status: Downloaded newer image for ghcr.io/tinglesoftware/dependabot-updater-npm:1.22
bin/update_script.rb:448:in `<main>': Security updates are enabled but a GitHub token is not supplied! Cannot proceed (StandardError)
Pull requests limit is set to zero. Security only updates are implied.
```
