### ISSUE TITLE
Referenced registries: '*,*' have not been configured in the root of dependabot.yml

### ISSUE THREAD

**Issue by Bafff** [tinglesoftware/dependabot-azure-devops#855]
**Describe the bug**
Starting `1.21.566` Since 27th September we are not able to run dependabot using ADO extension.. Version `1.20.543` was working fine

Error we receive:
`##[error]Referenced registries: '*,*' have not been configured in the root of dependabot.yml`

**To Reproduce**

We use such `./github/dependabot.yaml`
```
version: 2

registries:
  nuget-azure-devops:
    type: nuget-feed
    url: https://redacted.pkgs.visualstudio.com/_packaging/redacted/nuget/v3/index.json
    token: PAT:${{DEPENDABOT_TOKEN_ADO}}

updates:
- package-ecosystem: "nuget"
  directory: "/"
  schedule:
    interval: "weekly"
  target-branch: "master"
  registries: "*"
  versioning-strategy: increase
  ignore:
  # Disable packages updates to .NET 7/8 versions. Still, they would be updated for 6.*
  - dependency-name: "Microsoft.Extensions.Configuration"
    versions: ['7.*', '8.*']
  - dependency-name: "Microsoft.AspNetCore.Authentication.JwtBearer"
    versions: ['7.*', '8.*']
  - dependency-name: "Microsoft.Extensions.Configuration.Json"
    versions: ['7.*', '8.*']

- package-ecosystem: "docker"
  directory: "/.pipelines"
  schedule:
    interval: "weekly"
  target-branch: "master"
  registries: "*"
  versioning-strategy: increase
  ignore:
  # Disable image updates to .NET 7/8 versions. Still, it would be updated for 6.*
  - dependency-name: "*"
    update-types: ["version-update:semver-major"]
```

NuGet.Config configured in a such way:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="redacted-Azure-Feed" value="https://redacted.pkgs.visualstudio.com/_packaging/redacted/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

**Expected behavior**

Please help us understand why it stopped working in our configuration for all similarly configured pipelines

**Screenshots**
![image](https://github.com/tinglesoftware/dependabot-azure-devops/assets/26187677/8bd67518-c0a2-418f-885c-09f32944ad6a)

**Extension (please complete the following information):**
 - Host: Azure DevOps
 - Versions: 1.21.566-1.22.576

**Server (please complete the following information):**
 - Region: westeurope
