### ISSUE TITLE
BOM affecting commit & PR prefix

### ISSUE THREAD

**Issue by herbatnik** [tinglesoftware/dependabot-azure-devops#861]
**Describe the bug**
Configuring dependabot.yml with commit-message prefix works only when dependabot.yml file doesn't have BOM.

```yaml
updates:
  - package-ecosystem: nuget
    directory: "/"
    commit-message: 
      prefix: "(dependabot)"
  ...
```

**To Reproduce**
1. configure ADO extension to set some prefix via commit-message.prefix configuration in dependabot.yml
2. make sure BOM is set in the dependabot.yml
3. run pipeline

**Expected behavior**
PR and commit to be prefixed with configured prefix

**Extension (please complete the following information):**
 - Host: Azure DevOps
 - Version: 1.22.0.576

**Additional context**
If not easy to solve in short term, please do consider adding clear indication that BOM has to be removed from dependabot.yml.
I've figured that out while looking for similar issues in the Issues backlog, BOM did affect #740  :)
