### ISSUE TITLE
Nuget package is advertised to update when it is unlisted state

### ISSUE THREAD

**Issue by Bafff** [tinglesoftware/dependabot-azure-devops#863]
**Describe the bug**

task: dependabot@1 while checking nuget packages update package to the version that was marked as `Unlisted` in ADO feed

**To Reproduce**
- Configured nuget registy:

```
registries:
  nuget-azure-devops:
    type: nuget-feed
    url: https://redacted.pkgs.visualstudio.com/_packaging/redacted/nuget/v3/index.json
    token: PAT:${{DEPENDABOT_TOKEN_ADO}}

```
- Configured package-ecosystem:

```
- package-ecosystem: nuget
  directory: /
  schedule:
    interval: weekly
  target-branch: master
  registries:
    - nuget-azure-devops
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  ## Common ignore list for a .NET project
  ## Disable packages updates to .NET 7/8+ versions. Still, they would be updated for 6.*
  - dependency-name: "Microsoft.Extensions.*"
    update-types: ["version-update:semver-major"]
  - dependency-name: "Microsoft.AspNetCore.*"
    update-types: ["version-update:semver-major"]
  - dependency-name: "System.Text.Json"
    update-types: ["version-update:semver-major"]
  - dependency-name: "Microsoft.EntityFrameworkCore.*"
    update-types: ["version-update:semver-major"]
  ## Disable packages patch updates
  - dependency-name: "*"
    update-types: ["version-update:semver-patch"]
```

Unlisted latest version and made 12.1.41 the latest:
![image](https://github.com/tinglesoftware/dependabot-azure-devops/assets/26187677/00c81d60-8c8f-4c5d-8f73-d4093ce093dd)
![image](https://github.com/tinglesoftware/dependabot-azure-devops/assets/26187677/e2be993c-0aae-4041-afe0-43055c23ccef)

Received these results:

```
Bumps Redacted.Azure.Storage.DataAccess from 12.1.41 to 12.1.454769.

Commit:
Bump Redacted.Azure.Storage.DataAccess from 12.1.41 to 12.1.454769

Bumps Redacted.Azure.Storage.DataAccess from 12.1.41 to 12.1.454769.

Changes:

    ± Redacted/Redacted.Site.csproj
    ~~~
    --- /tmp/original20231027-8-kn7lsi	2023-10-27 14:31:06.711830700 +0000
    +++ /tmp/updated20231027-8-yaec0n	2023-10-27 14:31:06.711830700 +0000
    @@ -17,7 +17,7 @@
         <None Remove="wwwroot\img\promo\**" />
       </ItemGroup>
       <ItemGroup>
    -    <PackageReference Include="Redacted.Azure.Storage.DataAccess" Version="12.1.41" />
    +    <PackageReference Include="Redacted.Azure.Storage.DataAccess" Version="12.1.454769" />
         <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.21.0" />
       </ItemGroup>
       <ItemGroup>
    ~~~
    2 insertions (+), 2 deletions (-)
```

**Expected behavior**

The package `Redacted.Azure.Storage.DataAccess` should not be updated by dependabot

**Extension (please complete the following information):**
 - Host: Azure DevOps
 - Version:  ghcr.io/tinglesoftware/dependabot-updater-docker:1.22

Running using 

```
          - task: dependabot@1
            inputs:
              skipPullRequests: true
```
