### ISSUE TITLE
Is yarn supported?

### ISSUE THREAD

**Issue by sgabler-solytic** [tinglesoftware/dependabot-azure-devops#977]
Hi, not sure if this is a bug or a feature request. I'm also not a Frontend dev, so maybe I am missing something obvious, but is "yarn" supported as an ecosystem?

I get this error:

![image](https://github.com/tinglesoftware/dependabot-azure-devops/assets/55686147/fc31dcab-b1c5-4a89-b194-32c0a28753c4)

```
Starting: dependabot
    ==============================================================================
    Task         : Dependabot
    Description  : Automatically update dependencies and vulnerabilities in your code
    Version      : 1.26.627
    Author       : Tingle Software
    Help         : For help please visit https://github.com/tinglesoftware/dependabot-azure-devops
    ==============================================================================
    /usr/bin/docker run --rm -i -e DEPENDABOT_PACKAGE_MANAGER=yarn -e DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=1 -e DEPENDABOT_DIRECTORY=/ -e DEPENDABOT_TARGET_BRANCH=develop -e DEPENDABOT_IGNORE_CONDITIONS=[{"dependency-name":"*","update-types":["version-update:semver-major"]}] -e DEPENDABOT_COMMIT_MESSAGE_OPTIONS={"prefix":"🤖"} -e DEPENDABOT_FAIL_ON_EXCEPTION=true -e AZURE_ORGANIZATION=<redacted> -e AZURE_PROJECT=<redacted> -e AZURE_REPOSITORY=<redacted> -e AZURE_ACCESS_TOKEN=*** -e AZURE_MERGE_STRATEGY=squash ghcr.io/tinglesoftware/dependabot-updater-yarn:1.26 update_script
    Unable to find image 'ghcr.io/tinglesoftware/dependabot-updater-yarn:1.26' locally
    docker: Error response from daemon: Head "[https://ghcr.io/v2/tinglesoftware/dependabot-updater-yarn/manifests/1.26"](https://ghcr.io/v2/tinglesoftware/dependabot-updater-yarn/manifests/1.26%22): denied.
    See 'docker run --help'.
    ##[error]The process '/usr/bin/docker' failed with exit code 125
    Finishing: dependabot
```

Here is my pipeline definition:

```yml
trigger: none # Disable CI trigger
schedules:
  - cron: '0 4 * * 1-5' # daily at 4am UTC every weekday
    always: true
    branches:
      include:
        - develop
    batch: true
    displayName: Run dependabot every weekday
pool:
  vmImage: 'ubuntu-latest' # requires macos or ubuntu (windows is not supported)
steps:
  - task: dependabot@1
    inputs:
      setAutoComplete: false
```

And my dependabot config:

```yml
version: 2
updates:
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "🤖"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ] # Ignore major version updates
```

Browsing the package list here, it seems that there is no package for "yarn" available: https://github.com/orgs/tinglesoftware/packages?repo_name=dependabot-azure-devops.

My suspicion is that I am doing something wrong. 45 minutes of googling and reading issues here in this repo didn't yield a result, so I thought I'd best open a new issue.
