### ISSUE TITLE
Ruby type errors (includes Sorbet)

### ISSUE THREAD

**Issue by andybakerbrfc** [tinglesoftware/dependabot-azure-devops#999]
**Describe the bug**
Failure to update with error message:

> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/configuration.rb:296:in `call_validation_error_handler_default': Parameter 'credentials': Expected type T.nilable(Dependabot::Credential), got type Hash with value {"type"=>"git_source", "hos..."} (TypeError)

This is when fetching source from git using the token defined on line 142 of update_script.rb. This was on a script working prior to 1.26.2. The setup we use is simply:

```
trigger: none
variables:
  - group: "Dependabot"
schedules:
  - cron: "0 5 * * *"
    always: true
    branches:
      include:
        - main
    batch: true
    displayName: Daily
pool:
  vmImage: "ubuntu-latest"
steps:
  - task: npmAuthenticate@0
    inputs:
      workingFile: ".npmrc"
  - task: dependabot@1
    env:
      DEPENDABOT_PAT: $(common-feed-token)
```

I do not know ruby, but if I were to guess I say that the structure being created on line 142 no longer passes the type checking.

**To Reproduce**
1. Run the above pipeline on Azure on version 1.26.2

**Expected behavior**
The script to execute as before.

**Extension (please complete the following information):**
 - Host: Azure DevOps
 - Version 1.26.2

**Additional Info**
> Agent name: 'Hosted Agent'
> Current agent version: '3.234.0'
> Current image version: '20240212.1.0'
> Downloading task: npmAuthenticate (0.231.0)
> Downloading task: dependabot (1.26.659)
